package modchu.lib;

import java.util.List;
import java.util.Map;
import java.util.Random;
import java.util.UUID;

public interface Modchu_IEntityPlayer extends Modchu_IEntityHelper {
	public Object getDataWatcherWatchableObject(int i);
	public void setDataWatcherWatchableObject(int i, Object o);
	public void publicSetSize(float f, float f1);
	public void publicResetHeight();

	public void supersendChatToPlayer(Object chatMessageComponent);
	public boolean supercanUseCommand(int i, String s);
	public Object supergetPlayerCoordinates();
	public void superapplyEntityAttributes();
	public void superentityInit();
	public Object supergetItemInUse();
	public int supergetItemInUseCount();
	public boolean superisHandActive();
	public int supergetItemInUseDuration();
	public void superstopUsingItem();
	public void superclearItemInUse();
	public boolean superisBlocking();
	public void superonUpdate();
	public int supergetMaxInPortalTime();
	public int supergetPortalCooldown();
	public void superplaySound(String par1Str, float par2, float par3);
	public void superupdateItemUse(Object itemStack, int par2);
	public void superonItemUseFinish();
	public void superhandleStatusUpdate(byte par1);
	public boolean superisMovementBlocked();
	public void supercloseScreen();
	public boolean superstartRiding(Object entity);
	public void superupdateEntityActionState();
	public int supergetScore();
	public void supersetScore(int par1);
	public void superaddScore(int par1);
	public void superawardKillScore(Object entity, int par2);
	public Object superdropItem(boolean par1);
	public Object superdropPlayerItem(Object itemStack);
	public Object superdropItem(Object itemStack, boolean par2);
	public void superdropItemAndGetStack(Object entityItem);
	public float supergetCurrentPlayerStrVsBlock(Object block, boolean par2);
	public float supergetCurrentPlayerStrVsBlock(Object block, boolean par2, int meta);
	public boolean supercanHarvestBlock(Object block);
	public void superreadEntityFromNBT(Object nBTTagCompound);
	public void superwriteEntityToNBT(Object nBTTagCompound);
	public void superdisplayGUIChest(Object iInventory);
	public void superdisplayGUIHopper(Object tileEntityHopper);
	public void superdisplayGUIHopperMinecart(Object entityMinecartHopper);
	public void superopenGuiHorseInventory(Object entityHorse, Object iInventory);
	public void superdisplayGUIEnchantment(int par1, int par2, int par3, String par4Str);
	public void superdisplayGUIAnvil(int par1, int par2, int par3);
	public void superdisplayGUIWorkbench(int par1, int par2, int par3);
	public float supergetEyeHeight();
	public boolean superattackEntityFrom(Object damageSource, float par2);
	public boolean supercanAttackPlayer(Object entityPlayer);
	public void superdamageArmor(float par1);
	public int supergetTotalArmorValue();
	public float supergetArmorVisibility();
	public void superdamageEntity(Object damageSource, float par2);
	public void superdisplayGUIFurnace(Object tileEntityFurnace);
	public void superdisplayGUIDispenser(Object tileEntityDispenser);
	public void superdisplayGUIEditSign(Object tileEntity);
	public void superdisplayGUIBrewingStand(Object tileEntityBrewingStand);
	public void superdisplayGUIBeacon(Object tileEntityBeacon);
	public void superdisplayGUIMerchant(Object iMerchant, String par2Str);
	public void superopenBook(Object itemStack);
	public boolean superinteractWith(Object entity);
	public Object supergetHeldItemMainhand();
	public void superdestroyCurrentEquippedItem();
	public void superattackTargetEntityWithCurrentItem(Object entity);
	public void superonCriticalHit(Object entity);
	public void superonEnchantmentCritical(Object entity);
	public void superrespawnPlayer();
	public void supersetDead();
	public Object supersleepInBedAt(int par1, int par2, int par3);
	public float supergetBedOrientationInDegrees();
	public boolean superisPlayerSleeping();
	public boolean superisPlayerFullyAsleep();
	public int supergetSleepTimer();
	public boolean supergetHideCape(int par1);
	public void supersetHideCape(int par1, boolean par2);
	public void supersendMessage(Object par1Str);
	public Object supergetBedLocation();
	public boolean superisSpawnForced();
	public Object supergetBedLocation(int dimension);
	public boolean superisSpawnForced(int dimension);
	public void supersetSpawnChunk(Object chunkCoordinates, boolean par2);
	public void supersetSpawnChunk(Object chunkCoordinates, boolean forced, int dimension);
	public void superaddStat(Object statBase);
	public void superaddStat(Object statBase, int par2);
	public void superjump();
	public float supergetAIMoveSpeed();
	public void superaddMovementStat(double par1, double par3, double par5);
	public void superfall(float par1);
	public void superonKillEntity(Object entityLivingBase);
	public void supersetInWeb();
	public Object supergetItemIcon(Object itemStack, int par2);
	public Object supergetCurrentArmor(int par1);
	public void superaddExperience(int par1);
	public void superaddExperienceLevel(int par1);
	public int superxpBarCap();
	public void superaddExhaustion(float par1);
	public Object supergetFoodStats();
	public boolean supercanEat(boolean par1);
	public boolean supershouldHeal();
	public void supersetItemInUse(Object itemStack, int par2);
	public boolean superisCurrentToolAdventureModeExempt(int par1, int par2, int par3);
	public boolean supercanPlayerEdit(int par1, int par2, int par3, int par4, Object itemStack);
	public int supergetExperiencePoints(Object entityPlayer);
	public boolean superisPlayer();
	public String supergetEntityName();
	public boolean supergetAlwaysRenderNameTagForRender();
	public void superclonePlayer(Object entityPlayer, boolean par2);
	public boolean supercanTriggerWalking();
	public void supersendPlayerAbilities();
	public void supersetGameType(Object enumGameType);
	public String supergetName();
	public Object supergetEntityWorld();
	public Object supergetInventoryEnderChest();
	public Object supergetCurrentItemOrArmor(int par1);
	public Object supergetHeldItem();
	public void supersetCurrentItemOrArmor(int par1, Object itemStack);
	public boolean superisInvisibleToPlayer(Object entityPlayer);
	public Object[] supergetLastActiveItems();
	public boolean supergetHideCape();
	public boolean superisPushedByWater();
	public Object supergetWorldScoreboard();
	public Object supergetTeam();
	public String supergetTranslatedEntityName();
	public void supersetAbsorptionAmount(float par1);
	public float supergetAbsorptionAmount();
	public void superopenGui(Object mod, int modGuiId, Object world, int x, int y, int z);
	public float supergetDefaultEyeHeight();
	public String supergetDisplayName();
	public void superrefreshDisplayName();
	public void superupdateFallState(double par1, boolean par3);
	public boolean supercanBreatheUnderwater();
	public void superonEntityUpdate();
	public boolean superisChild();
	public void superonDeathUpdate();
	public int superdecreaseAirSupply(int par1);
	public Random supergetRNG();
	public Object supergetRevengeTarget();
	public int superfunc_142015_aE();
	public void supersetRevengeTarget(Object entityLivingBase);
	public Object supergetLastAttackedEntity();
	public int supergetLastAttackedEntityTime();
	public void supersetLastAttackedEntity(Object entity);
	public int supergetIdleTime();
	public void superupdatePotionEffects();
	public void superclearActivePotions();
	public Object supergetActivePotionEffects();
	public boolean superisPotionActive(int par1);
	public boolean superisPotionActive(Object potion);
	public Object supergetActivePotionEffect(Object potion);
	public void superaddPotionEffect(Object potionEffect);
	public boolean superisPotionApplicable(Object potionEffect);
	public boolean superisEntityUndead();
	public void superremovePotionEffectClient(int par1);
	public void superremovePotionEffect(int par1);
	public void superonNewPotionEffect(Object potionEffect);
	public void superonChangedPotionEffect(Object potionEffect, boolean par2);
	public void superonFinishedPotionEffect(Object potionEffect);
	public void superheal(float par1);
	public void superrenderBrokenItemStack(Object itemStack);
	public void superdropEquipment(boolean par1, int par2);
	public void superknockBack(Object entity, float par2, double par3, double par5);
	public String supergetDeathSound();
	public void superdropRareDrop(int par1);
	public void superdropFewItems(boolean par1, int par2);
	public boolean superisOnLadder();
	public boolean superisEntityAlive();
	public void superperformHurtAnimation();
	public Object superapplyArmorCalculations(Object damageSource, float par2);
	public Object superapplyPotionDamageCalculations(Object damageSource, float par2);
	public Object superfunc_110142_aN();
	public Object supergetAttackingEntity();
	public void superswingArm();
	public void superoutOfWorld();
	public void superupdateArmSwingProgress();
	public Object supergetEntityAttribute(Object attribute);
	public Object supergetAttributeMap();
	public void supersetSprinting(boolean par1);
	public float supergetSoundVolume();
	public float supergetSoundPitch();
	public void supersetPositionAndUpdate(double par1, double par3, double par5);
	public void superdismountEntity(Object entity);
	public boolean superisAIEnabled();
	public void supersetAIMoveSpeed(float par1);
	public boolean superattackEntityAsMob(Object entity);
	public float superupdateDistance(float par1, float par2);
	public void superupdateAITasks();
	public void supercollideWithNearbyEntities();
	public void supercollideWithEntity(Object entity);
	public void supersetPositionAndRotationDirect(double par1, double par3, double par5, float par7, float par8, int par9);
	public void superhandleJumpWater();
	public void supersetJumping(boolean par1);
	public void superonItemPickup(Object entity, int par2);
	public boolean supercanEntityBeSeen(Object entity);
	public Object supergetLookVec();
	public Object supergetLook(float par1);
	public float supergetSwingProgress(float par1);
	public Object supergetPosition(float par1);
	public Object superrayTrace(double par1, float par3);
	public boolean superisClientWorld();
	public boolean supercanBeCollidedWith();
	public boolean supercanBePushed();
	public void supersetBeenAttacked();
	public float supergetRotationYawHead();
	public void supersetRotationYawHead(float par1);
	public void supercurePotionEffects(Object itemStack);
	public boolean supershouldRiderFaceForward(Object entityPlayer);
	public Object supergetDataManager();
	//public boolean superequals(Object par1Obj);
	//public int superhashCode();
	public void supersetRotation(float par1, float par2);
	public void supersetPosition(double par1, double par3, double par5);
	public void superturn(float par1, float par2);
	public void supersetOnFireFromLava();
	public void supersetFire(int par1);
	public void superextinguish();
	public boolean superisOffsetPositionInLiquid(double par1, double par3, double par5);
	public void supermove(Object moverType, double par1, double par3, double par5);
	public void superdoBlockCollisions();
	public void superplayStepSound(int par1, int par2, int par3, int par4);
	public Object supergetCollisionBoundingBox();
	public void superdealFireDamage(int par1);
	public boolean superisWet();
	public boolean superisInWater();
	public boolean superhandleWaterMovement();
	public boolean superisInsideOfMaterial(Object material);
	public boolean superhandleLavaMovement();
	public void supermoveRelative(float par1, float par2, float par3);
	public int supergetBrightnessForRender(float par1);
	public float supergetBrightness(float par1);
	public void supersetWorld(Object world);
	public void supersetPositionAndRotation(double par1, double par3, double par5, float par7, float par8);
	public void supersetLocationAndAngles(double par1, double par3, double par5, float par7, float par8);
	public float supergetDistanceToEntity(Object entity);
	public double supergetDistanceSq(double par1, double par3, double par5);
	public double supergetDistance(double par1, double par3, double par5);
	public double supergetDistanceSqToEntity(Object entity);
	public void superonCollideWithPlayer(Object entityPlayer);
	public void superapplyEntityCollision(Object entity);
	public void superaddVelocity(double par1, double par3, double par5);
	public boolean superisInRangeToRenderVec3D(Object vec3);
	public boolean superisInRangeToRenderDist(double par1);
	public boolean superwriteToNBTAtomically(Object nBTTagCompound);
	public boolean superwriteToNBTOptional(Object nBTTagCompound);
	public void superwriteToNBT(Object nBTTagCompound);
	public void superreadFromNBT(Object nBTTagCompound);
	public boolean supershouldSetPosAfterLoading();
	public void superonChunkLoad();
	public Object supernewDoubleNBTList(double... par1ArrayOfDouble);
	public Object supernewFloatNBTList(float... par1ArrayOfFloat);
	public float supergetShadowSize();
	public Object superdropItem(int par1, int par2);
	public Object superdropItemWithOffset(int par1, int par2, float par3);
	public Object superentityDropItem(Object itemStack, float par2);
	public boolean superprocessInitialInteract(Object entityPlayer);
	public Object supergetCollisionBox(Object entity);
	public void superupdatePassenger();
	public float supergetCollisionBorderSize();
	public void supersetPortal(Object bockPos);
	public void supersetVelocity(double par1, double par3, double par5);
	public boolean superisBurning();
	public boolean superisRiding();
	public boolean superisSneaking();
	public void supersetSneaking(boolean par1);
	public boolean superisSprinting();
	public boolean superisInvisible();
	public void supersetInvisible(boolean par1);
	public boolean superisEating();
	public void supersetEating(boolean par1);
	public boolean supergetFlag(int par1);
	public void supersetFlag(int par1, boolean par2);
	public int supergetAir();
	public void supersetAir(int par1);
	public void superonStruckByLightning(Object entityLightningBolt);
	public Object[] supergetParts();
	public boolean superisEntityEqual(Object entity);
	public boolean supercanBeAttackedWithItem();
	public boolean superhitByEntity(Object entity);
	//public String supertoString();
	public boolean superisEntityInvulnerable();
	public void supercopyLocationAndAnglesFrom(Object entity);
	public void supercopyDataFrom(Object entity, boolean par2);
	public void superchangeDimension(int par1);
	public boolean supershouldExplodeBlock(Object explosion, Object world, int par3, int par4, int par5, int par6, float par7);
	public Object supergetLastPortalVec();
	public boolean superdoesEntityNotTriggerPressurePlate();
	public void superaddEntityCrashInfo(Object crashReportCategory);
	public boolean supercanRenderOnFire();
	public Object supergetEntityData();
	public boolean supershouldRiderSit();
	public Object supergetPickedResult(Object movingObjectPosition);
	public UUID supergetPersistentID();
	public boolean supershouldRenderInPass(int pass);
	public boolean superisCreatureType(Object enumCreatureType, boolean forSpawnCount);
	public String superregisterExtendedProperties(String identifier, Object iExtendedEntityProperties);
	public Object supergetExtendedProperties(String identifier);
	public boolean supercanRiderInteract();
	public boolean supershouldDismountInWater(Object entity);
	public boolean superpushOutOfBlocks(double d, double d1, double d2);
	public Object supercopyPlayer(Object entityplayer);
	public boolean superattackEntityFrom(Object damageSource, int par2);
	public void superwakeUpPlayer(boolean flag, boolean flag1, boolean flag2);
	public void superpreparePlayerToSpawn();
	public void supersetPositionCorrection(double par1, double par3, double par5);
	public void superonLivingUpdate();
	public void supermoveEntityWithHeading(float f, float f1);
	public String supergetHurtSound();
	public double supergetMountedYOffset();
	public void superresetHeight();
	public double supergetYOffset();
	public boolean superisEntityInsideOpaqueBlock();
	public Object supercopyInventory(Object inventoryplayer);
	public boolean superattackEntityFrom(Object entity, Object damageSource, int i);
	public int supergetMaxHealthInt();
	public int supergetHealthInt();
	public void supersetHealth(float f);
	public void supersetHealthInt(int i);
	public void supercloseScreenNoPacket();
	public void superfunc_146100_a(Object tileEntity);
	public void superfunc_146095_a(Object commandBlockLogic);
	public void superfunc_146093_a(Object tileEntityHopper);
	public void superfunc_146104_a(Object tileEntityBeacon);
	public void superfunc_146102_a(Object tileEntityDispenser);
	public void superfunc_146098_a(Object tileEntityBrewingStand);
	public void superfunc_146101_a(Object tileEntityFurnace);
	public void superaddChatMessage(Object iChatComponent);
	public void superaddChatComponentMessage(Object iChatComponent, boolean p_146105_2_);
	public String supergetSplashSound();
	public String supergetSwimSound();
	public float supergetBreakSpeed(Object block, boolean p_146096_2_, int meta);
	public float supergetBreakSpeed(Object block, boolean p_146096_2_, int meta, int x, int y, int z);
	public Object superfunc_146097_a(Object itemStack, boolean p_146097_2_, boolean p_146097_3_);
	public Object supergetGameProfile();
	public String superfunc_146067_o(int p_146067_1_);
	public Object supergetEquipmentInSlot(int par1);
	public Object superfunc_145748_c_();
	public boolean superfunc_146066_aG();
	public int supergetEntityId();
	public void supersetEntityId(int p_145769_1_);
	public void superfunc_145780_a(int p_145780_1_, int p_145780_2_, int p_145780_3_, Object block);
	public void superfunc_145775_I();
	public boolean superisInRangeToRender3d(double p_145770_1_, double p_145770_3_, double p_145770_5_);
	public Object superfunc_145778_a(Object item, int p_145778_2_, float p_145778_3_);
	public Object superdropItem(Object item, int p_145779_2_);
	public float superfunc_145772_a(Object explosion, Object world, int p_145772_3_, int p_145772_4_, int p_145772_5_, Object block);
	public boolean superfunc_145774_a(Object explosion, Object world, int p_145774_3_, int p_145774_4_, int p_145774_5_, Object block, float p_145774_7_);
	public void superfunc_145781_i(int p_145781_1_);
	public boolean superfunc_152122_n();
	public boolean superfunc_152123_o();
	public void superfunc_152121_a(Object type, Object resourceLocation);
	public void superfunc_152111_bt();
	public void superfunc_152112_bu();
	public void superonUpdateWalkingPlayer();
	public void superfunc_175159_q();
	public boolean superisUser();
	public void supersendHorseJump();
	public void supersendHorseInventory();
	public void supersetClientBrand(String brand);
	public String supergetClientBrand();
	public Object supergetPosition();
	public boolean superisServerWorld();
	public void superopenEditSign(Object tileEntitySign);
	public void superopenEditCommandBlock(Object commandBlockLogic);
	public void superdisplayGui(Object iInteractionObject);
	public void superdisplayVillagerTradeGui(Object iMerchant);
	public boolean superisCurrentViewEntity();
	public boolean superisSpectator();
	public boolean superhasPlayerInfo();
	public Object supergetPlayerInfo();
	public boolean superhasSkin();
	public String supergetSkinType();
	public float supergetFovModifier();
	public Object superdropItem(Object itemStack, boolean dropAround, boolean traceItem);
	public float supergetToolDigEfficiency(Object block);
	public float supergetBreakSpeed(Object iBlockState, Object blockPos);
	public Object supertrySleep(Object blockPos);
	public void supersetSpawnPoint(Object blockPos, boolean forced);
	public void superfunc_175145_a(Object statBase);
	public void superfall(float distance, float damageMultiplier);
	public String supergetFallSoundString(int damageValue);
	public int supergetXPSeed();
	public void superremoveExperienceLevel(int levels);
	public boolean superisAllowEdit();
	public boolean supercanPlayerEdit(Object blockPos, Object enumFacing, Object itemStack);
	public Object[] supergetInventory();
	public boolean supercanOpen(Object lockCode);
	public boolean superfunc_175148_a(Object enumPlayerModelParts);
	public boolean supersendCommandFeedback();
	public boolean superreplaceItemInInventory(int p_174820_1_, Object itemStack);
	public boolean superhasReducedDebug();
	public void supersetReducedDebug(boolean reducedDebug);
	public String supergetDisplayNameString();
	public void superonKillCommand();
	public void superfunc_180433_a(double p_180433_1_, boolean p_180433_3_, Object block, Object blockPos);
	public int supergetRevengeTimer();
	public void superfunc_175135_B();
	public void superfunc_175133_bi();
	public void superaddRandomDrop();
	public Object supergetCombatTracker();
	public float superfunc_175134_bD();
	public void superfunc_180466_bG();
	public void superfunc_180426_a(double p_180426_1_, double p_180426_3_, double p_180426_5_, float p_180426_7_, float p_180426_8_, int p_180426_9_, boolean p_180426_10_);
	public void superfunc_175136_bO();
	public void superplayStepSound(Object blockPos, Object block);
	public boolean superisSilent();
	public void supersetSilent(boolean isSilent);
	public void superspawnRunningParticles();
	public void supercreateRunningParticles();
	public boolean superisInLava();
	public void supermoveToBlockPosAndAngles(Object blockPos, float p_174828_2_, float p_174828_3_);
	public double supergetDistanceSq(Object blockPos);
	public double supergetDistanceSqToCenter(Object blockPos);
	public Object supergetPositionEyes(float p_174824_1_);
	public Object superdropItemWithOffset(Object item, int size, float p_145778_3_);
	public boolean superisEntityInvulnerable(Object damageSource);
	public void supercopyDataFromOld(Object entity);
	public float supergetExplosionResistance(Object explosion, Object world, Object blockPos, Object iBlockState);
	public boolean superfunc_174816_a(Object explosion, Object world, Object blockPos, Object iBlockState, float p_174816_5_);
	public int supergetMaxFallHeight();
	public void supersetCustomNameTag(String p_96094_1_);
	public String supergetCustomNameTag();
	public boolean superhasCustomName();
	public void supersetAlwaysRenderNameTag(boolean p_174805_1_);
	public boolean supergetAlwaysRenderNameTag();
	public Object supergetHorizontalFacing();
	public Object superfunc_174823_aP();
	public boolean superfunc_174827_a(Object entityPlayerMP);
	public Object supergetEntityBoundingBox();
	public void supersetEntityBoundingBox(Object axisAlignedBB);
	public boolean superisOutsideBorder();
	public void supersetOutsideBorder(boolean p_174821_1_);
	public Object supergetPositionVector();
	public Object supergetCommandSenderEntity();
	public void supersetCommandStat(Object type, int amount);
	public Object superfunc_174807_aT();
	public void superfunc_174817_o(Object entity);
	public Object superfunc_174819_aU();
	public void superfunc_174834_g(Object nBTTagCompound);
	public boolean superfunc_174825_a(Object entityPlayer, Object vec3);
	public boolean superfunc_180427_aV();
	public void superfunc_174815_a(Object entityLivingBase, Object entity);
	public void superheal(int par1);
	public void superdamageEntity(Object damageSource, int par2);
	public boolean superfunc_71066_bF();
	public void superupdateCloak();
	public void supersendChatToPlayer(String par1Str);
	public float supergetMaxHealthFloat();
	public boolean superfunc_96122_a(Object entityPlayer);
	public void superalertWolves(Object entityLiving, boolean par2);
	public void superdamageArmor(int par1);
	public float superfunc_82243_bO();
	public void superfunc_82162_bC();
	public boolean supercanCurrentToolHarvestBlock(int par1, int par2, int par3);
	public boolean superfunc_94062_bN();
	public boolean superfunc_94059_bO();
	public boolean supercanPickUpLoot();
	public Object supergetTranslator();
	public String supertranslateString(String par1Str, Object... par2ArrayOfObj);
	public boolean superfunc_98034_c(Object entityPlayer);
	public boolean superfunc_96092_aw();
	public int superfunc_96121_ay();
	public Object supergetLookHelper();
	public Object supergetMoveHelper();
	public Object supergetJumpHelper();
	public Object supergetNavigator();
	public Object supergetEntitySenses();
	public Object supergetLastAttackingEntity();
	public void supersetLastAttackingEntity(Object entity);
	public Object supergetAttackTarget();
	public void supersetAttackTarget(Object entityLiving);
	public boolean supercanAttackClass(Class par1Class);
	public void supereatGrassBonus();
	public boolean superisWithinHomeDistanceCurrentPosition();
	public boolean superisWithinHomeDistance(int par1, int par2, int par3);
	public void supersetHomeArea(int par1, int par2, int par3, int par4);
	public Object supergetHomePosition();
	public float supergetMaximumHomeDistance();
	public void superdetachHome();
	public boolean superhasHome();
	public String supergetTexture();
	public int supergetTalkInterval();
	public void superplayLivingSound();
	public void superspawnExplosionParticle();
	public float supergetHealth();
	public void supersetEntityHealth(int par1);
	public int superapplyArmorCalculations(Object damageSource, int par2);
	public int superapplyPotionDamageCalculations(Object damageSource, int par2);
	public String supergetAmbientSound();
	public void superknockBack(Object entity, int par2, double par3, double par5);
	public int supergetDropItemId();
	public void supersetMoveForward(float par1);
	public void superfunc_85033_bc();
	public boolean supercanDespawn();
	public void superdespawnEntity();
	public int supergetVerticalFaceSpeed();
	public void superfaceEntity(Object entity, float par2, float par3);
	public boolean supergetCanSpawnHere();
	public float supergetRenderSizeModifier();
	public int supergetMaxSpawnedInChunk();
	public void superonChangedPotionEffect(Object potionEffect);
	public float supergetSpeedModifier();
	public int superfunc_82143_as();
	public void superinitCreature();
	public boolean supercanBeSteered();
	public void superfunc_94058_c(String par1Str);
	public String superfunc_94057_bL();
	public boolean superfunc_94056_bM();
	public void superfunc_94061_f(boolean par1);
	public void superfunc_96120_a(int par1, float par2);
	public void supersetCanPickUpLoot(boolean par1);
	public boolean superfunc_104002_bU();
	public boolean superaddNotRiddenEntityID(Object nBTTagCompound);
	public boolean superaddEntityID(Object nBTTagCompound);
	public boolean superinteract(Object entityPlayer);
	public void superunmountEntity(Object entity);
	public boolean superfunc_85031_j(Object entity);
	public void superfunc_82149_j(Object entity);
	public float superfunc_82146_a(Object explosion, Object world, int par3, int par4, int par5, Object block);
	public boolean superfunc_96091_a(Object explosion, Object world, int par3, int par4, int par5, int par6, float par7);
	public void superfunc_85029_a(Object crashReportCategory);
	public void supersetSize(float f, float f1);
	public Object supergetCreatureAttribute();
	public void setPositionCorrection(double par1, double par3, double par5);
	public void superonDeath(Object par1DamageSource);
	public void supersendMotionUpdates();
	public void superupdateRidden();
	public void superfunc_110318_g();
	public void superfunc_110322_i();
	public void superfunc_142020_c(String par1Str);
	public String superfunc_142021_k();
	public boolean superisRidingHorse();
	public float supergetHorseJumpPower();
	public void supersetupCustomSkin();
	public Object supergetTextureSkin();
	public Object supergetTextureCape();
	public Object supergetLocationSkin();
	public Object supergetLocationCape();
	public boolean superstartRiding(Object entity, boolean force);
	public Object supergetRidingEntity();
	public void superdismountRidingEntity();
	public float supergetFOVMultiplier();
	public void supertravel(float f, float f1, float f2);
	public String supergetHurtSound(Object damageSource);
	public float supergetMaxHealth();
	public void superplaySound(Object par1Str, float par2, float par3);
	public void superdropLoot();
	public void supersetNoAI(boolean par1);
	public boolean superisNoDespawnRequired();
	public boolean superisOnSameTeam(Object entityLivingBase);
	public boolean superisOnTeam(Object team);
	public float supergetBlockExplosionResistance(Object explosion, Object world, int par3, int par4, int par5, Object block);
	public int supergetMaxSafePointTries();
	public UUID supergetUniqueID();
	public Object supergetStatFileWriter();
	public void supersendStatusMessage(Object iChatComponent, boolean p_146105_2_);
	public boolean supercanDropLoot();
	public void superonDataWatcherUpdate(int p_145781_1_);
	public void supersendEnterCombat();
	public void supersendEndCombat();
	public void supercloseScreenAndDropStack();
	public float supergetDigSpeed(Object iBlockState, Object blockPos);
	public void superonEnchant(Object itemStack, int levels);
	public boolean superisWearing(Object enumPlayerModelParts);
	public void superupdatePotionMetadata();
	public void superresetPotionEffectMetadata();
	public float supergetJumpUpwardsMotion();
	public void superhandleJumpLava();
	public void supersetPositionAndRotationDirect(double p_180426_1_, double p_180426_3_, double p_180426_5_, float p_180426_7_, float p_180426_8_, int p_180426_9_, boolean p_180426_10_);
	public void supermarkPotionsDirty();
	public boolean supercanExplosionDestroyBlock(Object explosion, Object world, Object blockPos, Object iBlockState, float p_174816_5_);
	public Object supergetHoverEvent();
	public boolean superisSpectatedByPlayer(Object entityPlayerMP);
	public Object supergetCommandStats();
	public Object supergetNBTTagCompound();
	public void superclientUpdateEntityNBT(Object nBTTagCompound);
	public boolean superinteractAt(Object entityPlayer, Object vec3);
	public boolean superisImmuneToExplosions();
	public void superapplyEnchantments(Object entityLivingBase, Object entity);
	public void supersetInPortal();
	public boolean superequals(Object p_equals_1_);
	public int superhashCode();
	public boolean superattackEntityFrom(Object damageSource, Object p_70097_2_);
	public Object supergetItemStackFromSlot(Object par1);
	public void supersetItemStackToSlot(Object entityEquipmentSlot, Object itemStack);
	public Object supergetItemStackFromSlot(int par1);
	public void superdisplayGuiEditCommandCart(Object commandBlockLogic);
	public void supertakeStat(Object statBase);
	public Object supergetFallSound(int damageValue);
	public void supersetCommandStats(Object entity);
	public void superswingArm(Object enumHand);
	public void superopenBook(Object itemStack, Object enumHand);
	public Object superinteract(Object entity, Object itemStack, Object enumHand);
	public void superupdatePassenger(Object entity);
	public boolean superprocessInitialInteract(Object entityPlayer, Object itemStack, Object enumHand);
	public void supersetRenderYawOffset(float p_181013_1_);
	public void superdropLoot(boolean p_184610_1_, int p_184610_2_, Object damageSource);
	public void superfrostWalk(Object blockPos);
	public void superplayEquipSound(Object itemStack);
	public Object superremoveActivePotionEffect(Object potion);
	public void superremovePotionEffect(Object potion);
	public void superplayHurtSound(Object damageSource);
	public void superdamageShield(float p_184590_1_);
	public Object supergetHeldItemOffhand();
	public Object supergetHeldItem(Object enumHand);
	public void supersetHeldItem(Object enumHand, Object itemStack);
	public Object supergetActiveHand();
	public void superupdateActiveHand();
	public void supersetActiveHand(Object enumHand);
	public Object supergetActiveItemStack();
	public int supergetItemInUseMaxCount();
	public void superstopActiveHand();
	public void superresetActiveHand();
	public boolean superisActiveItemStackBlocking();
	public boolean superisElytraFlying();
	public int supergetTicksElytraFlying();
	public boolean superattemptTeleport(double x, double y, double z);
	public boolean supercanBeHitWithPotion();
	public void superplayStepSound(int par1, int par2, int par3, Object par4);
	public boolean superisInRangeToRender3d(Object vec3);
	public boolean supershouldExplodeBlock(Object explosion, Object world, int par3, int par4, int par5, Object par6, float par7);
	public Object supergetTags();
	public boolean superaddTag(String tag);
	public boolean superremoveTag(String tag);
	public void supersetDropItemsWhenDead(boolean p_184174_1_);
	public void superdecrementTimeUntilPortal();
	public void superresetPositionToBB();
	public void superapplyOrientationToEntity(Object entity);
	public boolean supercanBeRidden(Object entity);
	public void superremovePassengers();
	public void superaddPassenger(Object entity);
	public void superremovePassenger(Object entity);
	public boolean supercanFitPassenger(Object entity);
	public Object supergetHeldEquipment();
	public Object supergetArmorInventoryList();
	public Object supergetEquipmentAndArmor();
	public boolean superisBeingRidden();
	public boolean superisGlowing();
	public void supersetGlowing(boolean p_184195_1_);
	public boolean superisOnScoreboardTeam(Object team);
	public void supersetEntityInvulnerable(boolean isInvulnerable);
	public boolean superisNonBoss();
	public void supersetUniqueId(UUID uniqueIdIn);
	public void supernotifyDataManagerChange(Object dataParameter);
	public Object supergetAdjustedHorizontalFacing();
	public Object supergetRenderBoundingBox();
	public Object supergetServer();
	public Object superapplyPlayerInteraction(Object entityPlayer, Object vec3d, Object itemStack, Object enumHand);
	public boolean superhasCapability(Object capability, Object enumFacing);
	public void superdeserializeNBT(Object nBTTagCompound);
	public Object superserializeNBT();
	public void superaddTrackingPlayer(Object entityPlayerMP);
	public void superremoveTrackingPlayer(Object entityPlayerMP);
	public float supergetRotatedYaw(Object rotation);
	public float supergetMirroredYaw(Object mirror);
	public boolean supersetPositionNonDirty();
	public Object supergetControllingPassenger();
	public Object supergetPassengers();
	public boolean superisPassenger(Object entity);
	public Object supergetRecursivePassengers();
	public Object supergetLowestRidingEntity();
	public boolean superisRidingSameEntity(Object entity);
	public boolean superisRidingOrBeingRiddenBy(Object entity);
	public boolean supercanPassengerSteer();
	public Object supergetPushReaction();
	public Object supergetSoundCategory();
	public Object supergetCapability(Object capability, Object enumFacing);
	public Object supergetRecursivePassengersByType(Class entityClass);
	public void supersetServerBrand(String brand);
	public String supergetServerBrand();
	public int supergetPermissionLevel();
	public void supersetPermissionLevel(int p_184839_1_);
	public void superdisplayGuiCommandBlock(Object tileEntityCommandBlock);
	public boolean superisRowingBoat();
	public boolean superisCreative();
	public boolean superisPlayerInfoSet();
	public Object supergetLocationElytra();
	public Object supercreateCooldownTracker();
	public void superupdateSize();
	public void superspawnSweepParticles();
	public boolean superhasAchievement(Object achievement);
	public Object supergetPrimaryHand();
	public void supersetPrimaryHand(Object enumHandSide);
	public float supergetCooldownPeriod();
	public float supergetCooledAttackStrength(float adjustTicks);
	public void superresetCooldown();
	public Object supergetCooldownTracker();
	public float supergetLuck();
	public void superaddPrefix(Object iTextComponent);
	public void superaddSuffix(Object iTextComponent);
	public Object supergetPrefixes();
	public Object supergetSuffixes();
	public boolean superignoreItemEntityData();
	public void supersetItemStackToSlot(int p_70062_1_, Object itemStack);
	public boolean superisNotColliding();
	public String supergetCachedUniqueIdString();
	public int supergetBrightnessForRender();
	public float supergetBrightness();
	public Object supergetTeleportDirection();
	public Object superfunc_181012_aH();
	public void superfunc_181013_g(float p_181013_1_);
	public void supersetAngles(float yaw, float pitch);
	public boolean supercanCommandSenderUseCommand(int permLevel, String commandName);
	public void superOnInsideBlock(Object iBlockState);
	public float superfunc_191954_d(float p_191954_1_);
	public boolean superfunc_191957_ae();
	public boolean superhasNoGravity();
	public void supersetNoGravity(boolean noGravity);
	public boolean superfunc_191953_am();
	public Object supergetPitchYaw();
	public Object supergetForward();
	public boolean supergetIsInvulnerable();
	public boolean supercanTrample(Object world, Object block, Object blockPos, float fallDistance);
	public int supergetFireImmuneTicks();
	public Map supergetActivePotionMap();
	public void superBlockUsingShield(Object entityLivingBase);
	public Object supergetLastDamageSource();
	public boolean superhasItemInSlot(Object entityEquipmentSlot);
	public float supergetWaterSlowDown();
	public boolean superattackable();
	public void supersetPartying(Object blockPos, boolean p_191987_2_);
	public boolean superprocessInitialInteract(Object entityPlayer, Object enumHand);
	public Object superapplyPlayerInteraction(Object entityPlayer, Object vec3d, Object enumHand);
	public Object supergetRecipeBook();
	public void superfunc_193103_a(Object iRecipe);
	public void superOpenEditStructure(Object tileEntityStructure);
	public boolean superisAutoJumpEnabled();
	public void superupdateAutoJump(float p_189810_1_, float p_189810_2_);
	public void superdestroyVanishingCursedItems();
	public void superdisableShield(boolean p_190777_1_);
	public void superunlockRecipes(List p_192021_1_);
	public void superunlockRecipes(Object[] resourceLocation);
	public void superfunc_192022_b(List p_192022_1_);
	public boolean superaddItemStackToInventory(Object itemStack);
	public boolean superaddShoulderEntity(Object nBTTagCompound);
	public void superspawnShoulderEntities();
	public Object supergetLeftShoulderEntity();
	public void supersetLeftShoulderEntity(Object nBTTagCompound);
	public Object supergetRightShoulderEntity();
	public void supersetRightShoulderEntity(Object nBTTagCompound);
	public boolean supercanUseCommandBlock();
	public boolean superhasSpawnDimension();
	public int supergetSpawnDimension();
	public void supersetSpawnDimension(Object integer);
	public void superonInitialSpawn(Object object, Object object2);

}
