package modchu.lib;

import java.util.Collection;
import java.util.Random;
import java.util.UUID;

public interface Modchu_IEntityOtherPlayerMP extends Modchu_IEntityLivingBase {
	public void superSendChatToPlayer(String par1Str);
	public int superGetMaxHealth();
	public boolean superCanAttackPlayer(Object entityPlayer);
	public void superAlertWolves(Object entityLiving, boolean par2);
	public float superGetArmorVisibility();
	public boolean superFunc_71066_bF();
	public boolean superCanCurrentToolHarvestBlock(int par1, int par2, int par3);
	public Object superGetTranslator();
	public String superTranslateString(String par1Str, Object... par2ArrayOfObj);
	public int superGetHealthInt();

	public void superSendChatToPlayer(Object chatMessageComponent);
	public void superSetupCustomSkin();
	public Object superGetTextureSkin();
	public Object superGetTextureCape();
	public Object superDropPlayerItem(Object itemStack);
	public float superGetCurrentPlayerStrVsBlock(Object block, boolean par2, int meta);
	public void superDisplayGUIHopper(Object tileEntityHopper);
	public void superDisplayGUIFurnace(Object tileEntityFurnace);
	public void superDisplayGUIDispenser(Object tileEntityDispenser);
	public void superDisplayGUIEditSign(Object tileEntity);
	public void superDisplayGUIBrewingStand(Object tileEntityBrewingStand);
	public void superDisplayGUIBeacon(Object tileEntityBeacon);
	public void superAddChatMessage(String par1Str);
	public String superGetEntityName();
	public Object superGetCurrentItemOrArmor(int par1);
	public boolean superIsInRangeToRenderVec3D(Object vec3);
	public boolean superShouldExplodeBlock(Object explosion, Object world, int par3, int par4, int par5, int par6, float par7);
	public Object superGetPlayerCoordinates();
	public boolean superHasPlayerInfo();
	public boolean superHasSkin();
	public void superFunc_152121_a(Object type, Object resourceLocation);
	public Object superDropItem(Object itemStack, boolean p_146097_2_, boolean p_146097_3_);
	public float superGetCurrentPlayerStrVsBlock(Object block, boolean p_146096_2_);
	public float superGetBreakSpeed(Object block, boolean p_146096_2_, int meta);
	public float superGetBreakSpeed(Object block, boolean p_146096_2_, int meta, int x, int y, int z);
	public void superFunc_146093_a(Object tileEntityHopper);
	public void superDisplayGUIHopperMinecart(Object entityMinecartHopper);
	public void superDisplayGUIEnchantment(int p_71002_1_, int p_71002_2_, int p_71002_3_, String p_71002_4_);
	public void superDisplayGUIAnvil(int p_82244_1_, int p_82244_2_, int p_82244_3_);
	public void superDisplayGUIWorkbench(int p_71058_1_, int p_71058_2_, int p_71058_3_);
	public void superFunc_146101_a(Object tileEntityFurnace);
	public void superFunc_146102_a(Object tileEntityDispenser);
	public void superFunc_146100_a(Object tileEntity);
	public void superFunc_146095_a(Object commandBlockLogic);
	public void superFunc_146098_a(Object tileEntityBrewingStand);
	public void superFunc_146104_a(Object tileEntityBeacon);
	public void superDisplayGUIMerchant(Object iMerchant, String p_71030_2_);
	public Object superSleepInBedAt(int p_71018_1_, int p_71018_2_, int p_71018_3_);
	public boolean superGetHideCape(int p_82241_1_);
	public void superSetHideCape(int p_82239_1_, boolean p_82239_2_);
	public void superSetSpawnChunk(Object chunkCoordinates, boolean p_71063_2_);
	public String superFunc_146067_o(int p_146067_1_);
	public boolean superIsCurrentToolAdventureModeExempt(int p_82246_1_, int p_82246_2_, int p_82246_3_);
	public boolean superCanPlayerEdit(int p_82247_1_, int p_82247_2_, int p_82247_3_, int p_82247_4_, Object itemStack);
	public boolean superGetHideCape();
	public boolean superHandleLavaMovement();
	public boolean superAttackEntityFrom(Object damageSource, float amount);
	public boolean superIsSpectator();
	public Object superGetPlayerInfo();
	public Object superGetLocationSkin();
	public Object superGetLocationCape();
	public String superGetSkinType();
	public float superGetFovModifier();
	public Object superGetItemInUse();
	public boolean superIsUsingItem();
	public int superGetItemInUseDuration();
	public void superStopUsingItem();
	public void superClearItemInUse();
	public void superCloseScreen();
	public int superGetScore();
	public void superSetScore(int p_85040_1_);
	public void superAddScore(int p_85039_1_);
	public Object superDropOneItem(boolean p_71040_1_);
	public Object superDropPlayerItemWithRandomChoice(Object itemStack, boolean unused);
	public Object superDropItemAndGetStack(Object entityItem);
	public float superGetToolDigEfficiency(Object block);
	public float superGetBreakSpeed(Object iBlockState, Object blockPos);
	public boolean superCanHarvestBlock(Object block);
	public void superDamageEntity(Object damageSource, float damageAmount);
	public void superOpenEditSign(Object tileEntitySign);
	public void superDisplayGuiEditCommandCart(Object commandBlockLogic);
	public void superDisplayVillagerTradeGui(Object iMerchant);
	public void superDisplayGUIChest(Object iInventory);
	public void superOpenGuiHorseInventory(Object entityHorse, Object iInventory);
	public void superDisplayGui(Object iInteractionObject);
	public void superOpenBook(Object itemStack);
	public boolean superInteractWith(Object entity);
	public void superDestroyCurrentEquippedItem();
	public void superAttackTargetEntityWithCurrentItem(Object entity);
	public void superOnCriticalHit(Object entity);
	public void superOnEnchantmentCritical(Object entity);
	public void superRespawnPlayer();
	public boolean superIsUser();
	public Object superGetGameProfile();
	public Object superTrySleep(Object blockPos);
	public void superWakeUpPlayer(boolean p_70999_1_, boolean updateWorldFlag, boolean setSpawn);
	public float superGetBedOrientationInDegrees();
	public boolean superIsPlayerFullyAsleep();
	public int superGetSleepTimer();
	public void superAddChatComponentMessage(Object iChatComponent);
	public Object superGetBedLocation();
	public boolean superIsSpawnForced();
	public void superSetSpawnPoint(Object blockPos, boolean forced);
	public void superAddStat(Object statBase);
	public void superAddStat(Object statBase, int amount);
	public void superTakeStat(Object statBase);
	public void superAddMovementStat(double p_71000_1_, double p_71000_3_, double p_71000_5_);
	public void superAddExperience(int amount);
	public int superGetXPSeed();
	public void superRemoveExperienceLevel(int levels);
	public void superAddExperienceLevel(int levels);
	public int superXpBarCap();
	public void superAddExhaustion(float p_71020_1_);
	public Object superGetFoodStats();
	public boolean superCanEat(boolean ignoreHunger);
	public boolean superShouldHeal();
	public void superSetItemInUse(Object itemStack, int duration);
	public boolean superIsAllowEdit();
	public boolean superCanPlayerEdit(Object blockPos, Object enumFacing, Object itemStack);
	public void superClonePlayer(Object entityPlayer, boolean respawnFromEnd);
	public void superSendPlayerAbilities();
	public void superSetGameType(Object gameType);
	public Object superGetInventoryEnderChest();
	public Object superGetHeldItem();
	public Object superGetWorldScoreboard();
	public boolean superCanOpen(Object lockCode);
	public boolean superIsWearing(Object enumPlayerModelParts);
	public boolean superHasReducedDebug();
	public void superSetReducedDebug(boolean reducedDebug);
	public void superOpenGui(Object mod, int modGuiId, Object world, int x, int y, int z);
	public Object superGetBedLocation(int dimension);
	public boolean superIsSpawnForced(int dimension);
	public void superSetSpawnChunk(Object blockPos, boolean forced, int dimension);
	public float superGetDefaultEyeHeight();
	public String superGetDisplayNameString();
	public void superRefreshDisplayName();
	public void superHeal(float healAmount);
	public void superSetHealth(float p_70606_1_);
	public boolean superWriteToNBTAtomically(Object nBTTagCompound);
	public boolean superInteractFirst(Object entityPlayer);
	public Object superGetCurrentArmor(int slotIn);
	// 190~
	public void superOpenBook(Object itemStack, Object enumHand);
	public Object superInteract(Object entity, Object itemStack, Object enumHand);
	public boolean superIsCreative();
	public boolean superIsPlayerInfoSet();
	public Object superGetLocationElytra();
	public Object superCreateCooldownTracker();
	public void superUpdateSize();
	public void superDisplayGuiCommandBlock(Object tileEntityCommandBlock);
	public void superSpawnSweepParticles();
	public boolean superHasAchievement(Object achievement);
	public Object superGetPrimaryHand();
	public void superSetPrimaryHand(Object enumHandSide);
	public float superGetCooldownPeriod();
	public float superGetCooledAttackStrength(float adjustTicks);
	public void superResetCooldown();
	public Object superGetCooldownTracker();
	public float superGetLuck();
	public void superAddPrefix(Object iTextComponent);
	public void superAddSuffix(Object iTextComponent);
	public Collection superGetPrefixes();
	public Collection superGetSuffixes();
	Object superGetLivingSound();
	public boolean superCanPickUpLoot();
	public Object superGetMoveHelper();
	public Object superGetJumpHelper();
	public Object superGetNavigator();
	public Object superGetEntitySenses();
	public Object superGetAttackTarget();
	public void superSetAttackTarget(Object entityLiving);
	public boolean superCanAttackClass(Class par1Class);
	public void superEatGrassBonus();
	public boolean superIsWithinHomeDistanceCurrentPosition();
	public Object superGetLookHelper();
	public void superPlayLivingSound();
	public void superSpawnExplosionParticle();
	public int superGetDropItemId();
	public void superSetMoveForward(float par1);
	public boolean superCanDespawn();
	public void superDespawnEntity();
	public int superGetVerticalFaceSpeed();
	public void superFaceEntity(Object entity, float par2, float par3);
	public boolean superGetCanSpawnHere();
	public float superGetRenderSizeModifier();
	public int superGetMaxSpawnedInChunk();
	public int superGetTalkInterval();
	public boolean superCanBeSteered();
	public void superSetCanPickUpLoot(boolean par1);
	public boolean superIsNoDespawnRequired();
	public boolean superProcessInteract(Object entityPlayer);

}
