package modchu.lib;

import java.util.HashMap;
import java.util.UUID;

public interface Modchu_IEntity extends Modchu_IEntityHelper {
	public int superGetEntityId();
	public void superSetEntityId(int p_145769_1_);
	public void superEntityInit();
	public void superReadEntityFromNBT(Object nBTTagCompound);
	public void superWriteEntityToNBT(Object nBTTagCompound);
	public Object superGetDataManager();
	//public boolean superEquals(Object p_equals_1_);
	//public int superHashCode();
	public void superPreparePlayerToSpawn();
	public void superSetDead();
	public void superSetSize(float p_70105_1_, float p_70105_2_);
	public void superSetRotation(float p_70101_1_, float p_70101_2_);
	public void superSetPosition(double p_70107_1_, double p_70107_3_, double p_70107_5_);
	public void superTurn(float p_70082_1_, float p_70082_2_);
	public void superOnUpdate();
	public void superOnEntityUpdate();
	public int superGetMaxInPortalTime();
	public void superSetOnFireFromLava();
	public void superSetFire(int p_70015_1_);
	public void superExtinguish();
	public void superOutOfWorld();
	public boolean superIsOffsetPositionInLiquid(double p_70038_1_, double p_70038_3_, double p_70038_5_);
	public void superMove(Object moverType, double p_70091_1_, double p_70091_3_, double p_70091_5_);
	public Object superGetSwimSound();
	public void superDoBlockCollisions();
	public void superFunc_145780_a(int p_145780_1_, int p_145780_2_, int p_145780_3_, Object block);
	public void superPlaySound(Object soundEvent, float p_85030_2_, float p_85030_3_);
	public boolean superCanTriggerWalking();
	public void superUpdateFallState(double p_70064_1_, boolean p_70064_3_);
	public Object superGetCollisionBoundingBox();
	public void superDealFireDamage(int p_70081_1_);
	public void superFall(float p_70069_1_);
	public boolean superIsWet();
	public boolean superIsInWater();
	public boolean superHandleWaterMovement();
	public Object superGetSplashSound();
	public boolean superIsInsideOfMaterial(Object material);
	public float superGetEyeHeight();
	public boolean superIsNotColliding();
	public int superGetBrightnessForRender(float p_70070_1_);
	public float superGetBrightness(float p_70013_1_);
	public void superSetWorld(Object world);
	public void superSetPositionAndRotation(double p_70080_1_, double p_70080_3_, double p_70080_5_, float p_70080_7_, float p_70080_8_);
	public void superSetLocationAndAngles(double p_70012_1_, double p_70012_3_, double p_70012_5_, float p_70012_7_, float p_70012_8_);
	public float superGetDistanceToEntity(Object entity);
	public double superGetDistanceSq(double p_70092_1_, double p_70092_3_, double p_70092_5_);
	public double superGetDistance(double p_70011_1_, double p_70011_3_, double p_70011_5_);
	public double superGetDistanceSqToEntity(Object entity);
	public void superOnCollideWithPlayer(Object entityPlayer);
	public void superApplyEntityCollision(Object entity);
	public void superAddVelocity(double p_70024_1_, double p_70024_3_, double p_70024_5_);
	public void superSetBeenAttacked();
	public boolean superAttackEntityFrom(Object damageSource, Object p_70097_2_);
	public boolean superCanBeCollidedWith();
	public boolean superCanBePushed();
	public void superAwardKillScore(Object entity, int p_70084_2_);
	public boolean superIsInRangeToRender3d(double p_145770_1_, double p_145770_3_, double p_145770_5_);
	public boolean superIsInRangeToRenderDist(double p_70112_1_);
	public boolean superWriteToNBTAtomically(Object nBTTagCompound);
	public boolean superWriteToNBTOptional(Object nBTTagCompound);
	public Object superWriteToNBT(Object nBTTagCompound);
	public void superReadFromNBT(Object nBTTagCompound);
	public boolean superShouldSetPosAfterLoading();
	public void superOnChunkLoad();
	public Object superNewDoubleNBTList(double... p_70087_1_);
	public Object superNewFloatNBTList(float... p_70049_1_);
	public Object superDropItem(Object item, int p_145779_2_);
	public Object superDropItemWithOffset(Object item, int p_145778_2_, float p_145778_3_);
	public Object superEntityDropItem(Object itemStack, float p_70099_2_);
	public float superGetShadowSize();
	public boolean superIsEntityAlive();
	public boolean superIsEntityInsideOpaqueBlock();
	public boolean superProcessInitialInteract(Object entityPlayer);
	public Object superGetCollisionBox(Object entity);
	public void superUpdateRidden();
	public void superUpdatePassenger();
	public double superGetYOffset();
	public double superGetMountedYOffset();
	public boolean superStartRiding(Object entity);
	public void superSetPositionAndRotationDirect(double p_70056_1_, double p_70056_3_, double p_70056_5_, float p_70056_7_, float p_70056_8_, int p_70056_9_);
	public float superGetCollisionBorderSize();
	public Object superGetLookVec();
	public void superSetPortal(Object blockPos);
	public int superGetPortalCooldown();
	public void superSetVelocity(double p_70016_1_, double p_70016_3_, double p_70016_5_);
	public void superHandleStatusUpdate(byte p_70103_1_);
	public void superPerformHurtAnimation();
	public Object[] superGetLastActiveItems();
	public void superSetItemStackToSlot(int p_70062_1_, Object itemStack);
	public boolean superIsBurning();
	public boolean superIsRiding();
	public boolean superIsSneaking();
	public void superSetSneaking(boolean p_70095_1_);
	public boolean superIsSprinting();
	public void superSetSprinting(boolean p_70031_1_);
	public boolean superIsInvisible();
	public boolean superIsInvisibleToPlayer(Object entityPlayer);
	public void superSetInvisible(boolean p_82142_1_);
	public boolean superIsEating();
	public void superSetEating(boolean p_70019_1_);
	public boolean superGetFlag(int p_70083_1_);
	public void superSetFlag(int p_70052_1_, boolean p_70052_2_);
	public int superGetAir();
	public void superSetAir(int p_70050_1_);
	public void superOnStruckByLightning(Object entityLightningBolt);
	public void superOnKillEntity(Object entityLivingBase);
	public boolean superPushOutOfBlocks(double p_145771_1_, double p_145771_3_, double p_145771_5_);
	public void superSetInWeb();
	public String superGetName();
	public Object[] superGetParts();
	public boolean superIsEntityEqual(Object entity);
	public float superGetRotationYawHead();
	public void superSetRotationYawHead(float p_70034_1_);
	public boolean superCanBeAttackedWithItem();
	public boolean superHitByEntity(Object entity);
	public boolean superIsEntityInvulnerable();
	public void superCopyLocationAndAnglesFrom(Object entity);
	public void superCopyDataFrom(Object entity, boolean p_82141_2_);
	public Object superChangeDimension(int p_71027_1_);
	public float superFunc_145772_a(Object explosion, Object world, int p_145772_3_, int p_145772_4_, int p_145772_5_, Object block);
	public boolean superFunc_145774_a(Object explosion, Object world, int p_145774_3_, int p_145774_4_, int p_145774_5_, Object block, float p_145774_7_);
	public int superGetMaxSafePointTries();
	public Object superGetLastPortalVec();
	public boolean superDoesEntityNotTriggerPressurePlate();
	public void superAddEntityCrashInfo(Object crashReportCategory);
	public boolean superCanRenderOnFire();
	public UUID superGetUniqueID();
	public boolean superIsPushedByWater();
	public Object superGetDisplayName();
	public void superOnDataWatcherUpdate(int p_145781_1_);
	public Object superGetEntityData();
	public boolean superShouldRiderSit();
	public Object superGetPickedResult(Object movingObjectPosition);
	public UUID superGetPersistentID();
	public boolean superShouldRenderInPass(int pass);
	public boolean superIsCreatureType(Object enumCreatureType, boolean forSpawnCount);
	public String superRegisterExtendedProperties(String identifier, Object iExtendedEntityProperties);
	public Object superGetExtendedProperties(String identifier);
	public boolean superCanRiderInteract();
	public boolean superShouldDismountInWater(Object entity);
	public void superSetCustomNameTag(String p_96094_1_);
	public String superGetCustomNameTag();
	public void superSetAlwaysRenderNameTag(boolean p_174805_1_);
	public boolean superGetAlwaysRenderNameTag();
	public boolean superInteract(Object entityPlayer);
	public Object superGetTeleportDirection();
	// ~164
	public void superPlayStepSound(int par1, int par2, int par3, Object par4);
	public boolean superIsInRangeToRender3d(Object vec3);
	public float superGetBlockExplosionResistance(Object explosion, Object world, int par3, int par4, int par5, Object block);
	public boolean superShouldExplodeBlock(Object explosion, Object world, int par3, int par4, int par5, Object par6, float par7);
	public String superGetTranslatedEntityName();
	// ~152
	public boolean superAttackEntityFrom(Object damageSource, int par2);
	public String superGetTexture();
	public boolean superAddNotRiddenEntityID(Object nBTTagCompound);
	public boolean superAddEntityID(Object nBTTagCompound);
	public boolean superInteractFirst(Object entityPlayer);
	public void superUnmountEntity(Object entity);
	public void superUpdateCloak();
	public float superFunc_82146_a(Object explosion, Object world, int par3, int par4, int par5, Object block);
	public boolean superFunc_96091_a(Object explosion, Object world, int par3, int par4, int par5, int par6, float par7);
	public int superGetMaxFallHeight();
	// 180~
	public void superOnKillCommand();
	public void superPlayStepSound(Object blockPos, Object block);
	public boolean superIsSilent();
	public void superSetSilent(boolean isSilent);
	public void superUpdateFallState(double p_180433_1_, boolean p_180433_3_, Object block, Object blockPos);
	public void superFall(float distance, float damageMultiplier);
	public void superDoWaterSplashEffect();
	public void superSpawnRunningParticles();
	public void superCreateRunningParticles();
	public boolean superIsInLava();
	public void superMoveToBlockPosAndAngles(Object blockPos, float p_174828_2_, float p_174828_3_);
	public double superGetDistanceSq(Object blockPos);
	public double superGetDistanceSqToCenter(Object blockPos);
	public Object superGetLook(float p_70676_1_);
	public Object superGetPositionEyes(float p_174824_1_);
	public Object superRayTrace(double p_174822_1_, float p_174822_3_);
	public void superSetPositionAndRotationDirect(double p_180426_1_, double p_180426_3_, double p_180426_5_, float p_180426_7_, float p_180426_8_, int p_180426_9_, boolean p_180426_10_);
	public Object[] superGetInventory();
	public boolean superIsEntityInvulnerable(Object damageSource);
	public void superCopyDataFromOld(Object entity);
	public float superGetExplosionResistance(Object explosion, Object world, Object blockPos, Object iBlockState);
	public boolean superVerifyExplosion(Object explosion, Object world, Object blockPos, Object iBlockState, float p_174816_5_);
	public boolean superHasCustomName();
	public void superSetPositionAndUpdate(double x, double y, double z);
	public boolean superGetAlwaysRenderNameTagForRender();
	public Object superGetHorizontalFacing();
	public Object superGetHoverEvent();
	public boolean superIsSpectatedByPlayer(Object entityPlayerMP);
	public Object superGetEntityBoundingBox();
	public void superSetEntityBoundingBox(Object axisAlignedBB);
	public boolean superIsOutsideBorder();
	public void superSetOutsideBorder(boolean p_174821_1_);
	public boolean superReplaceItemInInventory(int p_174820_1_, Object itemStack);
	public void superSendMessage(Object iTextComponent);
	public boolean superCanUseCommand(int permLevel, String commandName);
	public Object superGetPosition();
	public Object superGetPositionVector();
	public Object superGetEntityWorld();
	public Object superGetCommandSenderEntity();
	public boolean superSendCommandFeedback();
	public void superSetCommandStat(Object type, int amount);
	public Object superGetCommandStats();
	public void superSetCommandStats(Object entity);
	public Object superGetNBTTagCompound();
	public void superClientUpdateEntityNBT(Object nBTTagCompound);
	public boolean superInteractAt(Object entityPlayer, Object vec3);
	public boolean superIsImmuneToExplosions();
	public void superApplyEnchantments(Object entityLivingBase, Object entity);
	boolean superProcessInitialInteract(Object entityPlayer, Object itemStack, Object enumHand);
	// 190~
	public Object superGetTags();
	public boolean superAddTag(String tag);
	public boolean superRemoveTag(String tag);
	public boolean superEquals(Object p_equals_1_);
	public int superHashCode();
	public void superSetDropItemsWhenDead(boolean p_184174_1_);
	public void superDecrementTimeUntilPortal();
	public void superResetPositionToBB();
	public void superUpdatePassenger(Object entity);
	public void superApplyOrientationToEntity(Object entity);
	public boolean superStartRiding(Object entity, boolean force);
	public boolean superCanBeRidden(Object entity);
	public void superRemovePassengers();
	public void superDismountRidingEntity();
	public void superAddPassenger(Object entity);
	public void superRemovePassenger(Object entity);
	public boolean superCanFitPassenger(Object entity);
	public Object superGetHeldEquipment();
	public Object superGetArmorInventoryList();
	public Object superGetEquipmentAndArmor();
	public void superSetItemStackToSlot(Object entityEquipmentSlot, Object itemStack);
	public boolean superIsBeingRidden();
	public boolean superIsGlowing();
	public void superSetGlowing(boolean p_184195_1_);
	public Object superGetTeam();
	public boolean superIsOnSameTeam(Object entity);
	public boolean superIsOnScoreboardTeam(Object team);
	public void superSetRenderYawOffset(float offset);
	public void superSetEntityInvulnerable(boolean isInvulnerable);
	public boolean superIsNonBoss();
	public void superSetUniqueId(UUID uniqueIdIn);
	public void superNotifyDataManagerChange(Object dataParameter);
	public Object superGetAdjustedHorizontalFacing();
	public Object superGetRenderBoundingBox();
	public Object superGetServer();
	public Object superApplyPlayerInteraction(Object entityPlayer, Object vec3d, Object itemStack, Object enumHand);
	public boolean superHasCapability(Object capability, Object enumFacing);
	public Object superGetCapability(Object capability, Object enumFacing);
	public void superDeserializeNBT(Object nBTTagCompound);
	public Object superSerializeNBT();
	public void superAddTrackingPlayer(Object entityPlayerMP);
	public void superRemoveTrackingPlayer(Object entityPlayerMP);
	public float superGetRotatedYaw(Object rotation);
	public float superGetMirroredYaw(Object mirror);
	public boolean superIgnoreItemEntityData();
	public boolean superSetPositionNonDirty();
	public Object superGetControllingPassenger();
	public Object superGetPassengers();
	public boolean superIsPassenger(Object entity);
	public Object superGetRecursivePassengers();
	public Object superGetLowestRidingEntity();
	public boolean superIsRidingSameEntity(Object entity);
	public boolean superIsRidingOrBeingRiddenBy(Object entity);
	public boolean superCanPassengerSteer();
	public Object superGetRidingEntity();
	public Object superGetPushReaction();
	public Object superGetSoundCategory();
	public Object superGetRecursivePassengersByType(Class entityClass);
	public void superSetCurrentItemOrArmor(int p_70062_1_, Object itemStack);
	public int superGetBrightnessForRender();
	public float superGetBrightness();
	public void superAddToPlayerScore(Object entity, int p_70084_2_, Object damageSource);
	public void superMoveRelative(float p_70060_1_, float p_70060_2_, float p_70060_3_, float p_191958_4_);
	public void superFunc_181013_g(float p_181013_1_);
	public Object superFunc_181012_aH();
	public String superGetCachedUniqueIdString();
	public void superOnInsideBlock(Object iBlockState);
	public float superPlayFlySound(float p_191954_1_);
	public boolean superMakeFlySound();
	public boolean superHasNoGravity();
	public void superSetNoGravity(boolean noGravity);
	public boolean superIsOverWater();
	public Object superGetPitchYaw();
	public Object superGetForward();
	public boolean superGetIsInvulnerable();
	public boolean superCanTrample(Object world, Object block, Object blockPos, float fallDistance);
	public int superGetFireImmuneTicks();

}
