package modchu.lib;

import java.util.List;

public interface Modchu_IItemMaster {
	// ~152
	public int getDamageVsEntity(Object entity);
	public String getLocalizedName(Object itemStack);
	public String func_77653_i(Object itemStack);
	public boolean func_82788_x();
	public boolean isValidArmor(Object itemStack, int armorType);
	public int getItemDamageFromStack(Object itemStack);
	public int getItemDamageFromStackForDisplay(Object itemStack);
	public int getItemMaxDamageFromStack(Object itemStack);
	public boolean isItemStackDamaged(Object itemStack);
	public void setItemDamageForStack(Object itemStack, int damage);

	// 180~
	public boolean onItemUseFirst(Object itemStack, Object entityPlayer, Object world, Object blockPos, Object enumFacing, float hitX, float hitY, float hitZ);
	public boolean onBlockStartBreak(Object itemStack, Object blockPos, Object entityPlayer);
	public void renderHelmetOverlay(Object itemStack, Object entityPlayer, Object scaledResolution, float partialTicks);
	public int getMetadata(Object itemStack);
	public boolean onBlockDestroyed(Object itemStack, Object world, Object block, Object blockPos, Object entityLivingBase);
	public float getDigSpeed(Object itemStack, Object iBlockState);
	public boolean doesSneakBypassUse(Object world, Object blockPos, Object entityPlayer);

	// 172~
	public Object setMaxStackSize(int par1);
	public int getSpriteNumber();
	public Object getIconFromDamage(int par1);
	public Object getIconIndex(Object itemStack);
	public boolean onItemUse(Object itemStack, Object entityPlayer, Object world, int par4, int par5, int par6, int par7, float par8, float par9, float par10);
	public boolean onItemUse(Object itemStack, Object entityPlayer, Object world, Object blockPos, Object enumFacing, float f, float f1, float f2);
	public float func_150893_a(Object itemStack, Object block);
	public Object onItemRightClick(Object itemStack, Object world, Object entityPlayer);
	public Object onItemUseFinish(Object itemStack, Object world, Object entityPlayer);
	public int getItemStackLimit();
	public int getMetadata(int par1);
	public boolean getHasSubtypes();
	public Object setHasSubtypes(boolean par1);
	public int getMaxDamage();
	public Object setMaxDamage(int par1);
	public boolean isDamageable();
	public boolean hitEntity(Object itemStack, Object entityLivingBase, Object entityLivingBase1);
	public boolean onBlockDestroyed(Object itemStack, Object world, Object block, int p_150894_4_, int p_150894_5_, int p_150894_6_, Object entityLivingBase);
	public boolean func_150897_b(Object block);
	public boolean itemInteractionForEntity(Object itemStack, Object entityPlayer, Object entityLivingBase);
	public Object setFull3D();
	public boolean isFull3D();
	public boolean shouldRotateAroundWhenRendering();
	public Object setUnlocalizedName(String par1Str);
	public String getUnlocalizedNameInefficiently(Object itemStack);
	public String getUnlocalizedName();
	public String getUnlocalizedName(Object itemStack);
	public Object setContainerItem(Object item);
	public boolean doesContainerItemLeaveCraftingGrid(Object itemStack);
	public boolean getShareTag();
	public Object getContainerItem();
	public boolean hasContainerItem();
	public int getColorFromItemStack(Object itemStack, int par2);
	public void onUpdate(Object itemStack, Object world, Object entity, int par4, boolean par5);
	public void onCreated(Object itemStack, Object world, Object entityPlayer);
	public boolean isMap();
	public Object getItemUseAction(Object itemStack);
	public int getMaxItemUseDuration(Object itemStack);
	public void onPlayerStoppedUsing(Object itemStack, Object world, Object entityPlayer, int par4);
	public Object setPotionEffect(String par1Str);
	public String getPotionEffect(Object itemStack);
	public boolean isPotionIngredient(Object itemStack);
	public void addInformation(Object itemStack, Object entityPlayer, List par3List, boolean par4);
	public String getItemStackDisplayName(Object itemStack);
	public boolean hasEffect(Object itemStack);
	public Object getRarity(Object itemStack);
	public boolean isItemTool(Object itemStack);
	public Object rayTrace(Object world, Object entityPlayer, boolean par3);
	public int getItemEnchantability();
	public boolean requiresMultipleRenderPasses();
	public Object getIconFromDamageForRenderPass(int par1, int par2);
	public void getSubItems(Object item, Object creativeTabs, List p_150895_3_);
	public Object setCreativeTab(Object creativeTabs);
	public Object getCreativeTab();
	public boolean canItemEditBlocks();
	public boolean getIsRepairable(Object itemStack, Object itemStack1);
	public void registerIcons(Object iIconRegister);
	public Object getItemAttributeModifiers();
	public Object setTextureName(String par1Str);
	public String getIconString();
	public Object getAttributeModifiers(Object itemStack);
	public boolean onDroppedByPlayer(Object itemStack, Object entityPlayer);
	public boolean onItemUseFirst(Object itemStack, Object entityPlayer, Object world, int x, int y, int z, int side, float hitX, float hitY, float hitZ);
	public float getDigSpeed(Object itemStack, Object block, int metadata);
	public boolean isRepairable();
	public Object setNoRepair();
	public boolean onBlockStartBreak(Object itemStack, int X, int Y, int Z, Object entityPlayer);
	public void onUsingTick(Object itemStack, Object entityPlayer, int count);
	public boolean onLeftClickEntity(Object itemStack, Object entityPlayer, Object entity);
	public Object getIcon(Object itemStack, int renderPass, Object entityPlayer, Object itemStack1, int useRemaining);
	public int getRenderPasses(int metadata);
	public Object getContainerItem(Object itemStack);
	public boolean hasContainerItem(Object itemStack);
	public int getEntityLifespan(Object itemStack, Object world);
	public boolean hasCustomEntity(Object itemStack);
	public Object createEntity(Object world, Object entity, Object itemStack);
	public boolean onEntityItemUpdate(Object entityItem);
	public Object[] getCreativeTabs();
	public float getSmeltingExperience(Object itemStack);
	public Object getIcon(Object itemStack, int pass);
	public Object getChestGenBase(Object chestGenHooks, Object random, Object weightedRandomChestContent);
	public boolean doesSneakBypassUse(Object world, int x, int y, int z, Object entityPlayer);
	public void onArmorTick(Object world, Object entityPlayer, Object itemStack);
	public boolean isValidArmor(Object itemStack, Object entityEquipmentSlot, Object entity);
	public boolean isBookEnchantable(Object itemStack, Object itemStack1);
	public String getArmorTexture(Object itemStack, Object entity, Object entityEquipmentSlot, String type);
	public Object getFontRenderer(Object itemStack);
	public Object getArmorModel(Object entityLivingBase, Object itemStack, int armorSlot);
	public boolean onEntitySwing(Object entityLivingBase, Object itemStack);
	public void renderHelmetOverlay(Object itemStack, Object entityPlayer, Object scaledResolution, float partialTicks, boolean hasScreen, int mouseX, int mouseY);
	public int getDamage(Object itemStack);
	public int getDisplayDamage(Object itemStack);
	public boolean showDurabilityBar(Object itemStack);
	public double getDurabilityForDisplay(Object itemStack);
	public int getMaxDamage(Object itemStack);
	public boolean isDamaged(Object itemStack);
	public void setDamage(Object itemStack, int damage);
	public boolean canHarvestBlock(Object block, Object itemStack);
	public boolean hasEffect(Object itemStack, int pass);
	public int getItemStackLimit(Object itemStack);
	public void setHarvestLevel(String toolClass, int level);
	public Object getToolClasses(Object itemStack);
	public int getHarvestLevel(Object itemStack, String toolClass);

	// 164
	public float getStrVsBlock(Object itemStack, Object block);
	public boolean onBlockDestroyed(Object itemStack, Object world, int par3, int par4, int par5, int par6, Object entityLivingBase);
	public boolean canHarvestBlock(Object block);
	public String getStatName();
	public String getPotionEffect();
	public boolean isPotionIngredient();
	public String getItemDisplayName(Object itemStack);
	public void getSubItems(int par1, Object creativeTabs, List par3List);
	public float getStrVsBlock(Object itemStack, Object block, int metadata);
	public void onUsingItemTick(Object itemStack, Object entityPlayer, int count);
	public Object getContainerItemStack(Object itemStack);
	public boolean shouldPassSneakingClickToBlock(Object world, int par4, int par5, int par6);
	public void onArmorTickUpdate(Object world, Object entityPlayer, Object itemStack);
	public float getDamageVsEntity(Object entity, Object itemStack);
	public String getArmorTexture(Object itemStack, Object entity, int slot, int layer);
	// 190~
	public Object onItemUse(Object itemStack, Object entityPlayer, Object world, Object blockPos, Object enumHand, Object enumFacing, float f, float f1, float f2);
	public Object onItemRightClick(Object itemStack, Object world, Object entityPlayer, Object enumHand);
	public boolean itemInteractionForEntity(Object itemStack, Object entityPlayer, Object entityLivingBase, Object enumHand);
	public Object getItemAttributeModifiers(Object entityEquipmentSlot);
	public Object onItemUseFirst(Object itemStack, Object entityPlayer, Object world, Object blockPos, Object enumFacing, float hitX, float hitY, float hitZ, Object enumHand);
	public Object getArmorModel(Object entityLivingBase, Object itemStack, Object entityEquipmentSlot, Object modelBiped);
	public Object getAttributeModifiers(Object entityEquipmentSlot, Object itemStack);
	public boolean doesSneakBypassUse(Object itemStack, Object iBlockAccess, Object blockPos, Object entityPlayer);
	public Object getPropertyGetter(Object resourceLocation);
	public boolean updateItemStackNBT(Object nBTTagCompound);
	public boolean hasCustomProperties();
	public String getHighlightTip(Object itemStack, String displayName);
	public int getItemEnchantability(Object itemStack);
	public boolean isBeaconPayment(Object itemStack);
	public boolean shouldCauseReequipAnimation(Object itemStack, Object itemStack1, boolean slotChanged);
	public Object initCapabilities(Object itemStack, Object nBTTagCompound);
}
