package modchu.lib;

import java.util.UUID;

public interface Modchu_IEntityMaster {
	public void entityInit();
	public void readEntityFromNBT(Object nBTTagCompound);
	public void writeEntityToNBT(Object nBTTagCompound);
	public int getEntityId();
	public void setEntityId(int p_145769_1_);
	public Object getDataWatcher();
	public boolean equals(Object p_equals_1_);
	public int hashCode();
	public void preparePlayerToSpawn();
	public void setDead();
	public void setSize(float p_70105_1_, float p_70105_2_);
	public void setRotation(float p_70101_1_, float p_70101_2_);
	public void setPosition(double p_70107_1_, double p_70107_3_, double p_70107_5_);
	public void setAngles(float p_70082_1_, float p_70082_2_);
	public void onUpdate();
	public void onEntityUpdate();
	public int getMaxInPortalTime();
	public void setOnFireFromLava();
	public void setFire(int p_70015_1_);
	public void extinguish();
	public void kill();
	public boolean isOffsetPositionInLiquid(double p_70038_1_, double p_70038_3_, double p_70038_5_);
	public void moveEntity(double p_70091_1_, double p_70091_3_, double p_70091_5_);
	public String getSwimSound();
	public void func_145775_I();
	public void func_145780_a(int p_145780_1_, int p_145780_2_, int p_145780_3_, Object block);
	public void playSound(String p_85030_1_, float p_85030_2_, float p_85030_3_);
	public boolean canTriggerWalking();
	public void updateFallState(double p_70064_1_, boolean p_70064_3_);
	public Object getBoundingBox();
	public void dealFireDamage(int p_70081_1_);
	public void fall(float p_70069_1_);
	public boolean isWet();
	public boolean isInWater();
	public boolean handleWaterMovement();
	public String getSplashSound();
	public boolean isInsideOfMaterial(Object material);
	public float getEyeHeight();
	public boolean handleLavaMovement();
	public void moveFlying(float p_70060_1_, float p_70060_2_, float p_70060_3_);
	public int getBrightnessForRender(float p_70070_1_);
	public float getBrightness(float p_70013_1_);
	public void setWorld(Object world);
	public void setPositionAndRotation(double p_70080_1_, double p_70080_3_, double p_70080_5_, float p_70080_7_, float p_70080_8_);
	public void setLocationAndAngles(double p_70012_1_, double p_70012_3_, double p_70012_5_, float p_70012_7_, float p_70012_8_);
	public float getDistanceToEntity(Object entity);
	public double getDistanceSq(double p_70092_1_, double p_70092_3_, double p_70092_5_);
	public double getDistance(double p_70011_1_, double p_70011_3_, double p_70011_5_);
	public double getDistanceSqToEntity(Object entity);
	public void onCollideWithPlayer(Object entityPlayer);
	public void applyEntityCollision(Object entity);
	public void addVelocity(double p_70024_1_, double p_70024_3_, double p_70024_5_);
	public void setBeenAttacked();
	public boolean attackEntityFrom(Object damageSource, float p_70097_2_);
	public boolean canBeCollidedWith();
	public boolean canBePushed();
	public void addToPlayerScore(Object entity, int p_70084_2_);
	public boolean isInRangeToRender3d(double p_145770_1_, double p_145770_3_, double p_145770_5_);
	public boolean isInRangeToRenderDist(double p_70112_1_);
	public boolean writeMountToNBT(Object nBTTagCompound);
	public boolean writeToNBTOptional(Object nBTTagCompound);
	public void writeToNBT(Object nBTTagCompound);
	public void readFromNBT(Object nBTTagCompound);
	public boolean shouldSetPosAfterLoading();
	public void onChunkLoad();
	public Object newDoubleNBTList(double... p_70087_1_);
	public Object newFloatNBTList(float... p_70049_1_);
	public Object dropItem(Object item, int p_145779_2_);
	public Object func_145778_a(Object item, int p_145778_2_, float p_145778_3_);
	public Object entityDropItem(Object itemStack, float p_70099_2_);
	public float getShadowSize();
	public boolean isEntityAlive();
	public boolean isEntityInsideOpaqueBlock();
	public boolean interactFirst(Object entityPlayer);
	public Object getCollisionBox(Object entity);
	public void updateRidden();
	public void updateRiderPosition();
	public double getYOffset();
	public double getMountedYOffset();
	public void mountEntity(Object entity);
	public void setPositionAndRotation2(double p_70056_1_, double p_70056_3_, double p_70056_5_, float p_70056_7_, float p_70056_8_, int p_70056_9_);
	public float getCollisionBorderSize();
	public Object getLookVec();
	public void setInPortal();
	public int getPortalCooldown();
	public void setVelocity(double p_70016_1_, double p_70016_3_, double p_70016_5_);
	public void handleHealthUpdate(byte p_70103_1_);
	public void performHurtAnimation();
	public Object[] getLastActiveItems();
	public void setCurrentItemOrArmor(int p_70062_1_, Object itemStack);
	public boolean isBurning();
	public boolean isRiding();
	public boolean isSneaking();
	public void setSneaking(boolean p_70095_1_);
	public boolean isSprinting();
	public void setSprinting(boolean p_70031_1_);
	public boolean isInvisible();
	public boolean isInvisibleToPlayer(Object entityPlayer);
	public void setInvisible(boolean p_82142_1_);
	public boolean isEating();
	public void setEating(boolean p_70019_1_);
	public boolean getFlag(int p_70083_1_);
	public void setFlag(int p_70052_1_, boolean p_70052_2_);
	public int getAir();
	public void setAir(int p_70050_1_);
	public void onStruckByLightning(Object entityLightningBolt);
	public void onKillEntity(Object entityLivingBase);
	public boolean func_145771_j(double p_145771_1_, double p_145771_3_, double p_145771_5_);
	public void setInWeb();
	public String getCommandSenderName();
	public Object[] getParts();
	public boolean isEntityEqual(Object entity);
	public float getRotationYawHead();
	public void setRotationYawHead(float p_70034_1_);
	public boolean canAttackWithItem();
	public boolean hitByEntity(Object entity);
	public String toString();
	public boolean isEntityInvulnerable();
	public void copyLocationAndAnglesFrom(Object entity);
	public void copyDataFrom(Object entity, boolean p_82141_2_);
	public void travelToDimension(int p_71027_1_);
	public float func_145772_a(Object explosion, Object world, int p_145772_3_, int p_145772_4_, int p_145772_5_, Object block);
	public boolean func_145774_a(Object explosion, Object world, int p_145774_3_, int p_145774_4_, int p_145774_5_, Object block, float p_145774_7_);
	public int getMaxSafePointTries();
	public int getTeleportDirection();
	public boolean doesEntityNotTriggerPressurePlate();
	public void addEntityCrashInfo(Object crashReportCategory);
	public boolean canRenderOnFire();
	public UUID getUniqueID();
	public boolean isPushedByWater();
	public Object func_145748_c_();
	public void func_145781_i(int p_145781_1_);
	public Object getEntityData();
	public boolean shouldRiderSit();
	public Object getPickedResult(Object movingObjectPosition);
	public UUID getPersistentID();
	public boolean shouldRenderInPass(int pass);
	public boolean isCreatureType(Object enumCreatureType, boolean forSpawnCount);
	public String registerExtendedProperties(String identifier, Object iExtendedEntityProperties);
	public Object getExtendedProperties(String identifier);
	public boolean canRiderInteract();
	public boolean shouldDismountInWater(Object entity);

}
