package modchu.lib;

import java.util.UUID;

public interface Modchu_IEntityTameable extends Modchu_IEntityTameableB {
	public void superCurePotionEffects(Object itemStack);
	public boolean superShouldRiderFaceForward(Object entityPlayer);
	public Object superGetEntityData();
	public boolean superShouldRiderSit();
	public Object superGetPickedResult(Object movingObjectPosition);
	public UUID superGetPersistentID();
	public boolean superShouldRenderInPass(int pass);
	public boolean superIsCreatureType(Object enumCreatureType, boolean forSpawnCount);
	public String superRegisterExtendedProperties(String identifier, Object iExtendedEntityProperties);
	public Object superGetExtendedProperties(String identifier);
	public boolean superCanRiderInteract();
	public boolean superShouldDismountInWater(Object entity);
	public Object superGetOwner();
	public Object superGetPlayerInLove();
	public boolean superIsWithinHomeDistanceCurrentPosition();
	public void superUpdateLeashedState();
	public Object superGetDropItem();
	public Object superGetEquipmentInSlot(int par1);
	public boolean superCanDropLoot();
	public String superGetFallSoundString(int p_146067_1_);
	public Object superGetEntityAttribute(Object iAttribute);
	public int superGetEntityId();
	public void superSetEntityId(int p_145769_1_);
	public String superGetSwimSound();
	public String superGetSplashSound();
	public boolean superIsInRangeToRender3d(double p_145770_1_, double p_145770_3_, double p_145770_5_);
	public Object superDropItem(Object item, int p_145779_2_);
	public Object superDropItemWithOffset(Object item, int p_145778_2_, float p_145778_3_);
	public boolean superPushOutOfBlocks(double p_145771_1_, double p_145771_3_, double p_145771_5_);
	public float superGetExplosionResistance(Object explosion, Object world, Object blockPos, Object iBlockState);
	public boolean superVerifyExplosion(Object explosion, Object world, Object blockPos, Object iBlockState, float f);
	public Object superGetDisplayName();
	public void superOnDataWatcherUpdate(int p_145781_1_);
	public void superAttackEntity(Object entity, float par2);
	public float superGetBlockPathWeight(int par1, int par2, int par3);
	public Object superFindPlayerToAttack();
	public boolean superIsMovementCeased();
	public void superUpdateWanderPath();
	public void superSetPathToEntity(Object pathEntity);
	public Object superGetEntityToAttack();
	public void superSetTarget(Object entity);
	public void superSetHomeArea(int par1, int par2, int par3, int par4);
	public float superFunc_110174_bM();
	public boolean superIsAIEnabled();
	public int superGetMaxSafePointTries();
	public Object superFunc_130225_q(int par1);
	public Object[] superGetLastActiveItems();
	public void superFunc_110163_bv();
	public void superEnchantEquipment();
	public boolean superHasCustomNameTag();
	public void superUpdateFallState(double par1, boolean par3);
	public int superFunc_142015_aE();
	public void superFall(float par1);
	public void superDropRareDrop(int par1);
	public Object superFunc_110142_aN();
	public void superSetPositionAndRotation2(double par1, double par3, double par5, float par7, float par8, int par9);
	public Object superGetPosition(float par1);
	public Object superRayTrace(double par1, float par3);
	public boolean superIsClientWorld();
	public float superGetShadowSize();
	public boolean superIsEntityInvulnerable();
	public void superCopyDataFrom(Object entity, boolean par2);
	public Object superOnInitialSpawn(Object iEntityLivingData);
	public void superFunc_146082_f(Object entityPlayer);
	public boolean superIsWithinHomeDistance(int par1, int par2, int par3);
	public String superGetCommandSenderName();
	public Object superGetItemIcon(Object itemStack, int par2);
	public void superFunc_145775_I();
	public void superFunc_145780_a(int p_145780_1_, int p_145780_2_, int p_145780_3_, Object block);
	public float superGetExplosionResistance(Object explosion, Object world, int p_145772_3_, int p_145772_4_, int p_145772_5_, Object block);
	public boolean superFunc_145774_a(Object explosion, Object world, int p_145774_3_, int p_145774_4_, int p_145774_5_, Object block, float p_145774_7_);
	public void superUpdateEntityActionState();
	public float superFunc_145772_a(Object explosion, Object world, int p_145772_3_, int p_145772_4_, int p_145772_5_, Object block);
	public float superGetBlockPathWeight(Object blockPos);
	public String superFunc_152113_b();
	public void superFunc_152115_b(String par1Str);
	public String superFunc_146067_o(int p_146067_1_);
	public Object superFunc_145778_a(Object item, int p_145778_2_, float p_145778_3_);
	public boolean superIsWithinHomeDistanceFromPosition(Object blockPos);

}
