package modchu.lib;

import java.util.Random;
import java.util.UUID;

public interface Modchu_IEntityOtherPlayerMP {
	public void superUpdateCloak();
	public void superSendChatToPlayer(String par1Str);
	public int superGetMaxHealth();
	public boolean superFunc_96122_a(Object entityPlayer);
	public void superAlertWolves(Object entityLiving, boolean par2);
	public void superDamageArmor(int par1);
	public float superFunc_82243_bO();
	public boolean superFunc_71066_bF();
	public void superFunc_82162_bC();
	public boolean superCanCurrentToolHarvestBlock(int par1, int par2, int par3);
	public boolean superFunc_94062_bN();
	public boolean superFunc_94059_bO();
	public boolean superCanPickUpLoot();
	public Object superGetTranslator();
	public String superTranslateString(String par1Str, Object... par2ArrayOfObj);
	public boolean superFunc_98034_c(Object entityPlayer);
	public boolean superFunc_96092_aw();
	public int superFunc_96121_ay();
	public Object superGetLookHelper();
	public Object superGetMoveHelper();
	public Object superGetJumpHelper();
	public Object superGetNavigator();
	public Object superGetEntitySenses();
	public Object superGetAttackTarget();
	public void superSetAttackTarget(Object entityLiving);
	public boolean superCanAttackClass(Class par1Class);
	public void superEatGrassBonus();
	public boolean superIsWithinHomeDistanceCurrentPosition();
	public boolean superIsWithinHomeDistance(int par1, int par2, int par3);
	public void superSetHomeArea(int par1, int par2, int par3, int par4);
	public Object superGetHomePosition();
	public float superGetMaximumHomeDistance();
	public void superDetachHome();
	public String superGetTexture();
	public int superGetTalkInterval();
	public void superPlayLivingSound();
	public void superSpawnExplosionParticle();
	public int superGetHealthInt();
	public String superGetLivingSound();
	public int superGetDropItemId();
	public void superSetMoveForward(float par1);
	public void superFunc_85033_bc();
	public boolean superCanDespawn();
	public void superDespawnEntity();
	public int superGetVerticalFaceSpeed();
	public void superFaceEntity(Object entity, float par2, float par3);
	public boolean superGetCanSpawnHere();
	public float superGetRenderSizeModifier();
	public int superGetMaxSpawnedInChunk();
	public float superGetSpeedModifier();
	public int superFunc_82143_as();
	public void superInitCreature();
	public boolean superCanBeSteered();
	public void superFunc_94058_c(String par1Str);
	public String superFunc_94057_bL();
	public boolean superFunc_94056_bM();
	public void superFunc_94061_f(boolean par1);
	public void superFunc_96120_a(int par1, float par2);
	public void superSetCanPickUpLoot(boolean par1);
	public boolean superFunc_104002_bU();
	public boolean superAddNotRiddenEntityID(Object nBTTagCompound);
	public boolean superAddEntityID(Object nBTTagCompound);
	public boolean superInteract(Object entityPlayer);
	public void superUnmountEntity(Object entity);
	public boolean superFunc_85031_j(Object entity);
	public void superFunc_82149_j(Object entity);
	public float superFunc_82146_a(Object explosion, Object world, int par3, int par4, int par5, Object block);
	public boolean superFunc_96091_a(Object explosion, Object world, int par3, int par4, int par5, int par6, float par7);
	public void superFunc_85029_a(Object crashReportCategory);

	public void superSendChatToPlayer(Object chatMessageComponent);
	public void superSetupCustomSkin();
	public Object superGetTextureSkin();
	public Object superGetTextureCape();
	public Object superDropPlayerItem(Object itemStack);
	public float superGetCurrentPlayerStrVsBlock(Object block, boolean par2, int meta);
	public void superDisplayGUIHopper(Object tileEntityHopper);
	public void superDisplayGUIFurnace(Object tileEntityFurnace);
	public void superDisplayGUIDispenser(Object tileEntityDispenser);
	public void superDisplayGUIEditSign(Object tileEntity);
	public void superDisplayGUIBrewingStand(Object tileEntityBrewingStand);
	public void superDisplayGUIBeacon(Object tileEntityBeacon);
	public void superAddChatMessage(String par1Str);
	public String superGetEntityName();
	public Object superGetCurrentItemOrArmor(int par1);
	public String superGetTranslatedEntityName();
	public void superPlayStepSound(int par1, int par2, int par3, int par4);
	public boolean superIsInRangeToRenderVec3D(Object vec3);
	public Object superDropItem(int par1, int par2);
	public Object superDropItemWithOffset(int par1, int par2, float par3);
	public float superGetBlockExplosionResistance(Object explosion, Object world, int par3, int par4, int par5, Object block);
	public boolean superShouldExplodeBlock(Object explosion, Object world, int par3, int par4, int par5, int par6, float par7);


	public void superSetPositionAndRotation2(double p_70056_1_, double p_70056_3_, double p_70056_5_, float p_70056_7_, float p_70056_8_, int p_70056_9_);
	public float superGetShadowSize();
	public boolean superCanCommandSenderUseCommand(int p_70003_1_, String p_70003_2_);
	public Object superGetPlayerCoordinates();
	public boolean superFunc_152122_n();
	public boolean superFunc_152123_o();
	public void superFunc_152121_a(Object type, Object resourceLocation);
	public Object superFunc_146097_a(Object itemStack, boolean p_146097_2_, boolean p_146097_3_);
	public float superGetCurrentPlayerStrVsBlock(Object block, boolean p_146096_2_);
	public float superGetBreakSpeed(Object block, boolean p_146096_2_, int meta);
	public float superGetBreakSpeed(Object block, boolean p_146096_2_, int meta, int x, int y, int z);
	public void superFunc_146093_a(Object tileEntityHopper);
	public void superDisplayGUIHopperMinecart(Object entityMinecartHopper);
	public void superDisplayGUIEnchantment(int p_71002_1_, int p_71002_2_, int p_71002_3_, String p_71002_4_);
	public void superDisplayGUIAnvil(int p_82244_1_, int p_82244_2_, int p_82244_3_);
	public void superDisplayGUIWorkbench(int p_71058_1_, int p_71058_2_, int p_71058_3_);
	public void superFunc_146101_a(Object tileEntityFurnace);
	public void superFunc_146102_a(Object tileEntityDispenser);
	public void superFunc_146100_a(Object tileEntity);
	public void superFunc_146095_a(Object commandBlockLogic);
	public void superFunc_146098_a(Object tileEntityBrewingStand);
	public void superFunc_146104_a(Object tileEntityBeacon);
	public void superDisplayGUIMerchant(Object iMerchant, String p_71030_2_);
	public Object superSleepInBedAt(int p_71018_1_, int p_71018_2_, int p_71018_3_);
	public boolean superGetHideCape(int p_82241_1_);
	public void superSetHideCape(int p_82239_1_, boolean p_82239_2_);
	public void superSetSpawnChunk(Object chunkCoordinates, boolean p_71063_2_);
	public void superFall(float p_70069_1_);
	public String superFunc_146067_o(int p_146067_1_);
	public Object superGetItemIcon(Object itemStack, int p_70620_2_);
	public boolean superIsCurrentToolAdventureModeExempt(int p_82246_1_, int p_82246_2_, int p_82246_3_);
	public boolean superCanPlayerEdit(int p_82247_1_, int p_82247_2_, int p_82247_3_, int p_82247_4_, Object itemStack);
	public String superGetCommandSenderName();
	public Object[] superGetLastActiveItems();
	public boolean superGetHideCape();
	public Object superFunc_145748_c_();
	public Object superGetPosition(float par1);
	public void superUpdateFallState(double p_70064_1_, boolean p_70064_3_);
	public int superFunc_142015_aE();
	public void superDropRareDrop(int p_70600_1_);
	public Object superFunc_110142_aN();
	public boolean superIsAIEnabled();
	public void superUpdateAITasks();
	public boolean superIsClientWorld();
	public void superFunc_145775_I();
	public void superFunc_145780_a(int p_145780_1_, int p_145780_2_, int p_145780_3_, Object block);
	public boolean superHandleLavaMovement();
	public Object superFunc_145778_a(Object item, int p_145778_2_, float p_145778_3_);
	public boolean superFunc_145771_j(double p_145771_1_, double p_145771_3_, double p_145771_5_);
	public boolean superIsEntityInvulnerable();
	public void superCopyDataFrom(Object entity, boolean p_82141_2_);
	public float superFunc_145772_a(Object explosion, Object world, int p_145772_3_, int p_145772_4_, int p_145772_5_, Object block);
	public boolean superFunc_145774_a(Object explosion, Object world, int p_145774_3_, int p_145774_4_, int p_145774_5_, Object block, float p_145774_7_);
	public int superGetMaxSafePointTries();

	public boolean superAttackEntityFrom(Object damageSource, float amount);
	public void superFunc_180426_a(double p_180426_1_, double p_180426_3_, double p_180426_5_, float p_180426_7_, float p_180426_8_, int p_180426_9_, boolean p_180426_10_);
	public void superOnUpdate();
	public void superOnLivingUpdate();
	public void superSetCurrentItemOrArmor(int slotIn, Object itemStack);
	public void superAddChatMessage(Object iChatComponent);
	public boolean superCanUseCommand(int permLevel, String commandName);
	public Object superGetPosition();
	public boolean superIsSpectator();
	public boolean superHasPlayerInfo();
	public Object superGetPlayerInfo();
	public boolean superHasSkin();
	public Object superGetLocationSkin();
	public Object superGetLocationCape();
	public String superGetSkinType();
	public float superGetFovModifier();
	public void superApplyEntityAttributes();
	public void superEntityInit();
	public Object superGetItemInUse();
	public int superGetItemInUseCount();
	public boolean superIsUsingItem();
	public int superGetItemInUseDuration();
	public void superStopUsingItem();
	public void superClearItemInUse();
	public boolean superIsBlocking();
	public int superGetMaxInPortalTime();
	public String superGetSwimSound();
	public String superGetSplashSound();
	public int superGetPortalCooldown();
	public void superPlaySound(String name, float volume, float pitch);
	public void superUpdateItemUse(Object itemStack, int p_71010_2_);
	public void superOnItemUseFinish();
	public void superHandleHealthUpdate(byte p_70103_1_);
	public boolean superIsMovementBlocked();
	public void superCloseScreen();
	public void superUpdateRidden();
	public void superPreparePlayerToSpawn();
	public void superUpdateEntityActionState();
	public int superGetScore();
	public void superSetScore(int p_85040_1_);
	public void superAddScore(int p_85039_1_);
	public void superOnDeath(Object damageSource);
	public String superGetHurtSound();
	public String superGetDeathSound();
	public void superAddToPlayerScore(Object entity, int amount);
	public Object superDropOneItem(boolean p_71040_1_);
	public Object superDropPlayerItemWithRandomChoice(Object itemStack, boolean unused);
	public Object superDropItem(Object itemStack, boolean dropAround, boolean traceItem);
	public void superJoinEntityItemWithWorld(Object entityItem);
	public float superGetToolDigEfficiency(Object block);
	public float superGetBreakSpeed(Object iBlockState, Object blockPos);
	public boolean superCanHarvestBlock(Object block);
	public void superReadEntityFromNBT(Object nBTTagCompound);
	public void superWriteEntityToNBT(Object nBTTagCompound);
	public boolean superCanAttackPlayer(Object entityPlayer);
	public void superDamageArmor(float p_70675_1_);
	public int superGetTotalArmorValue();
	public float superGetArmorVisibility();
	public void superDamageEntity(Object damageSource, float damageAmount);
	public void superOpenEditSign(Object tileEntitySign);
	public void superOpenEditCommandBlock(Object commandBlockLogic);
	public void superDisplayVillagerTradeGui(Object iMerchant);
	public void superDisplayGUIChest(Object iInventory);
	public void superDisplayGUIHorse(Object entityHorse, Object iInventory);
	public void superDisplayGui(Object iInteractionObject);
	public void superDisplayGUIBook(Object itemStack);
	public boolean superInteractWith(Object entity);
	public Object superGetCurrentEquippedItem();
	public void superDestroyCurrentEquippedItem();
	public double superGetYOffset();
	public void superAttackTargetEntityWithCurrentItem(Object entity);
	public void superOnCriticalHit(Object entity);
	public void superOnEnchantmentCritical(Object entity);
	public void superRespawnPlayer();
	public void superSetDead();
	public boolean superIsEntityInsideOpaqueBlock();
	public boolean superIsUser();
	public Object superGetGameProfile();
	public Object superTrySleep(Object blockPos);
	public void superWakeUpPlayer(boolean p_70999_1_, boolean updateWorldFlag, boolean setSpawn);
	public float superGetBedOrientationInDegrees();
	public boolean superIsPlayerSleeping();
	public boolean superIsPlayerFullyAsleep();
	public int superGetSleepTimer();
	public void superAddChatComponentMessage(Object iChatComponent);
	public Object superGetBedLocation();
	public boolean superIsSpawnForced();
	public void superSetSpawnPoint(Object blockPos, boolean forced);
	public void superTriggerAchievement(Object statBase);
	public void superAddStat(Object statBase, int amount);
	public void superFunc_175145_a(Object statBase);
	public void superJump();
	public void superMoveEntityWithHeading(float p_70612_1_, float p_70612_2_);
	public float superGetAIMoveSpeed();
	public void superAddMovementStat(double p_71000_1_, double p_71000_3_, double p_71000_5_);
	public void superFall(float distance, float damageMultiplier);
	public void superResetHeight();
	public String superGetFallSoundString(int damageValue);
	public void superOnKillEntity(Object entityLivingBase);
	public void superSetInWeb();
	public Object superGetCurrentArmor(int slotIn);
	public void superAddExperience(int amount);
	public int superGetXPSeed();
	public void superRemoveExperienceLevel(int levels);
	public void superAddExperienceLevel(int levels);
	public int superXpBarCap();
	public void superAddExhaustion(float p_71020_1_);
	public Object superGetFoodStats();
	public boolean superCanEat(boolean ignoreHunger);
	public boolean superShouldHeal();
	public void superSetItemInUse(Object itemStack, int duration);
	public boolean superIsAllowEdit();
	public boolean superCanPlayerEdit(Object blockPos, Object enumFacing, Object itemStack);
	public int superGetExperiencePoints(Object entityPlayer);
	public boolean superIsPlayer();
	public boolean superGetAlwaysRenderNameTagForRender();
	public void superClonePlayer(Object entityPlayer, boolean respawnFromEnd);
	public boolean superCanTriggerWalking();
	public void superSendPlayerAbilities();
	public void superSetGameType(Object gameType);
	public String superGetName();
	public Object superGetInventoryEnderChest();
	public Object superGetEquipmentInSlot(int slotIn);
	public Object superGetHeldItem();
	public boolean superIsInvisibleToPlayer(Object entityPlayer);
	public Object[] superGetInventory();
	public boolean superIsPushedByWater();
	public Object superGetWorldScoreboard();
	public Object superGetTeam();
	public Object superGetDisplayName();
	public float superGetEyeHeight();
	public void superSetAbsorptionAmount(float amount);
	public float superGetAbsorptionAmount();
	public boolean superCanOpen(Object lockCode);
	public boolean superFunc_175148_a(Object enumPlayerModelParts);
	public boolean superSendCommandFeedback();
	public boolean superReplaceItemInInventory(int p_174820_1_, Object itemStack);
	public boolean superHasReducedDebug();
	public void superSetReducedDebug(boolean reducedDebug);
	public void superOpenGui(Object mod, int modGuiId, Object world, int x, int y, int z);
	public Object superGetBedLocation(int dimension);
	public boolean superIsSpawnForced(int dimension);
	public void superSetSpawnChunk(Object blockPos, boolean forced, int dimension);
	public float superGetDefaultEyeHeight();
	public String superGetDisplayNameString();
	public void superRefreshDisplayName();
	public void superOnKillCommand();
	public void superFunc_180433_a(double p_180433_1_, boolean p_180433_3_, Object block, Object blockPos);
	public boolean superCanBreatheUnderwater();
	public void superOnEntityUpdate();
	public boolean superIsChild();
	public void superOnDeathUpdate();
	public boolean superFunc_146066_aG();
	public int superDecreaseAirSupply(int p_70682_1_);
	public Random superGetRNG();
	public Object superGetAITarget();
	public int superGetRevengeTimer();
	public void superSetRevengeTarget(Object entityLivingBase);
	public Object superGetLastAttacker();
	public int superGetLastAttackerTime();
	public void superSetLastAttacker(Object entity);
	public int superGetAge();
	public void superUpdatePotionEffects();
	public void superFunc_175135_B();
	public void superFunc_175133_bi();
	public void superClearActivePotions();
	public Object superGetActivePotionEffects();
	public boolean superIsPotionActive(int p_82165_1_);
	public boolean superIsPotionActive(Object potion);
	public Object superGetActivePotionEffect(Object potion);
	public void superAddPotionEffect(Object potionEffect);
	public boolean superIsPotionApplicable(Object potionEffect);
	public boolean superIsEntityUndead();
	public void superRemovePotionEffectClient(int p_70618_1_);
	public void superRemovePotionEffect(int p_82170_1_);
	public void superOnNewPotionEffect(Object potionEffect);
	public void superOnChangedPotionEffect(Object potionEffect, boolean p_70695_2_);
	public void superOnFinishedPotionEffect(Object potionEffect);
	public void superHeal(float healAmount);
	public void superSetHealth(float p_70606_1_);
	public void superRenderBrokenItemStack(Object itemStack);
	public void superDropEquipment(boolean p_82160_1_, int p_82160_2_);
	public void superKnockBack(Object entity, float p_70653_2_, double p_70653_3_, double p_70653_5_);
	public void superAddRandomArmor();
	public void superDropFewItems(boolean p_70628_1_, int p_70628_2_);
	public boolean superIsOnLadder();
	public boolean superIsEntityAlive();
	public void superPerformHurtAnimation();
	public float superApplyArmorCalculations(Object damageSource, float p_70655_2_);
	public float superApplyPotionDamageCalculations(Object damageSource, float p_70672_2_);
	public Object superGetCombatTracker();
	public Object superFunc_94060_bK();
	public void superSwingItem();
	public void superKill();
	public void superUpdateArmSwingProgress();
	public Object superGetEntityAttribute(Object iAttribute);
	public Object superGetAttributeMap();
	public Object superGetCreatureAttribute();
	public void superSetSprinting(boolean sprinting);
	public float superGetSoundVolume();
	public float superGetSoundPitch();
	public void superDismountEntity(Object entity);
	public float superFunc_175134_bD();
	public void superUpdateAITick();
	public void superFunc_180466_bG();
	public void superSetAIMoveSpeed(float p_70659_1_);
	public boolean superAttackEntityAsMob(Object entity);
	public float superFunc_110146_f(float p_110146_1_, float p_110146_2_);
	public void superCollideWithNearbyEntities();
	public void superCollideWithEntity(Object entity);
	public void superMountEntity(Object entity);
	public void superSetJumping(boolean p_70637_1_);
	public void superOnItemPickup(Object entity, int p_71001_2_);
	public boolean superCanEntityBeSeen(Object entity);
	public Object superGetLookVec();
	public Object superGetLook(float p_70676_1_);
	public float superGetSwingProgress(float p_70678_1_);
	public boolean superIsServerWorld();
	public boolean superCanBeCollidedWith();
	public boolean superCanBePushed();
	public void superSetBeenAttacked();
	public float superGetRotationYawHead();
	public void superSetRotationYawHead(float rotation);
	public boolean superIsOnSameTeam(Object entityLivingBase);
	public boolean superIsOnTeam(Object team);
	public void superFunc_152111_bt();
	public void superFunc_152112_bu();
	public void superFunc_175136_bO();
	public void superCurePotionEffects(Object itemStack);
	public boolean superShouldRiderFaceForward(Object entityPlayer);
	public int superGetEntityId();
	public void superSetEntityId(int id);
	public Object superGetDataWatcher();
	public void superSetSize(float width, float height);
	public void superSetRotation(float yaw, float pitch);
	public void superSetPosition(double x, double y, double z);
	public void superSetAngles(float yaw, float pitch);
	public void superSetOnFireFromLava();
	public void superSetFire(int seconds);
	public void superExtinguish();
	public boolean superIsOffsetPositionInLiquid(double x, double y, double z);
	public void superMoveEntity(double x, double y, double z);
	public void superDoBlockCollisions();
	public void superPlayStepSound(Object blockPos, Object block);
	public boolean superIsSilent();
	public void superSetSilent(boolean isSilent);
	public Object superGetBoundingBox();
	public void superDealFireDamage(int amount);
	public boolean superIsWet();
	public boolean superIsInWater();
	public boolean superHandleWaterMovement();
	public void superSpawnRunningParticles();
	public void superCreateRunningParticles();
	public boolean superIsInsideOfMaterial(Object material);
	public boolean superIsInLava();
	public void superMoveFlying(float strafe, float forward, float friction);
	public int superGetBrightnessForRender(float p_70070_1_);
	public float superGetBrightness(float p_70013_1_);
	public void superSetWorld(Object world);
	public void superSetPositionAndRotation(double x, double y, double z, float yaw, float pitch);
	public void superMoveToBlockPosAndAngles(Object blockPos, float p_174828_2_, float p_174828_3_);
	public void superSetLocationAndAngles(double x, double y, double z, float yaw, float pitch);
	public float superGetDistanceToEntity(Object entity);
	public double superGetDistanceSq(double x, double y, double z);
	public double superGetDistanceSq(Object blockPos);
	public double superGetDistanceSqToCenter(Object blockPos);
	public double superGetDistance(double x, double y, double z);
	public double superGetDistanceSqToEntity(Object entity);
	public void superOnCollideWithPlayer(Object entityPlayer);
	public void superApplyEntityCollision(Object entity);
	public void superAddVelocity(double x, double y, double z);
	public Object superGetPositionEyes(float p_174824_1_);
	public Object superRayTrace(double p_174822_1_, float p_174822_3_);
	public boolean superIsInRangeToRender3d(double x, double y, double z);
	public boolean superIsInRangeToRenderDist(double distance);
	public boolean superWriteMountToNBT(Object nBTTagCompound);
	public boolean superWriteToNBTOptional(Object nBTTagCompound);
	public void superWriteToNBT(Object nBTTagCompound);
	public void superReadFromNBT(Object nBTTagCompound);
	public boolean superShouldSetPosAfterLoading();
	public void superOnChunkLoad();
	public Object superNewDoubleNBTList(double... numbers);
	public Object superNewFloatNBTList(float... numbers);
	public Object superDropItem(Object item, int size);
	public Object superDropItemWithOffset(Object item, int size, float p_145778_3_);
	public Object superEntityDropItem(Object itemStack, float offsetY);
	public boolean superInteractFirst(Object entityPlayer);
	public Object superGetCollisionBox(Object entity);
	public void superUpdateRiderPosition();
	public double superGetMountedYOffset();
	public float superGetCollisionBorderSize();
	public void superSetInPortal();
	public void superSetVelocity(double x, double y, double z);
	public boolean superIsBurning();
	public boolean superIsRiding();
	public boolean superIsSneaking();
	public void superSetSneaking(boolean sneaking);
	public boolean superIsSprinting();
	public boolean superIsInvisible();
	public void superSetInvisible(boolean invisible);
	public boolean superIsEating();
	public void superSetEating(boolean eating);
	public boolean superGetFlag(int flag);
	public void superSetFlag(int flag, boolean set);
	public int superGetAir();
	public void superSetAir(int air);
	public void superOnStruckByLightning(Object entityLightningBolt);
	public boolean superPushOutOfBlocks(double x, double y, double z);
	public Object[] superGetParts();
	public boolean superIsEntityEqual(Object entity);
	public boolean superCanAttackWithItem();
	public boolean superHitByEntity(Object entity);
	public boolean superIsEntityInvulnerable(Object damageSource);
	public void superCopyLocationAndAnglesFrom(Object entity);
	public void superCopyDataFromOld(Object entity);
	public void superTravelToDimension(int dimensionId);
	public float superGetExplosionResistance(Object explosion, Object world, Object blockPos, Object iBlockState);
	public boolean superFunc_174816_a(Object explosion, Object world, Object blockPos, Object iBlockState, float p_174816_5_);
	public int superGetMaxFallHeight();
	public int superGetTeleportDirection();
	public boolean superDoesEntityNotTriggerPressurePlate();
	public void superAddEntityCrashInfo(Object crashReportCategory);
	public boolean superCanRenderOnFire();
	public UUID superGetUniqueID();
	public void superSetCustomNameTag(String p_96094_1_);
	public String superGetCustomNameTag();
	public boolean superHasCustomName();
	public void superSetAlwaysRenderNameTag(boolean p_174805_1_);
	public boolean superGetAlwaysRenderNameTag();
	public void superSetPositionAndUpdate(double x, double y, double z);
	public void superFunc_145781_i(int p_145781_1_);
	public Object superGetHorizontalFacing();
	public Object superFunc_174823_aP();
	public boolean superFunc_174827_a(Object entityPlayerMP);
	public Object superGetEntityBoundingBox();
	public void superSetEntityBoundingBox(Object axisAlignedBB);
	public boolean superIsOutsideBorder();
	public void superSetOutsideBorder(boolean p_174821_1_);
	public Object superGetPositionVector();
	public Object superGetEntityWorld();
	public Object superGetCommandSenderEntity();
	public void superSetCommandStat(Object type, int amount);
	public Object superFunc_174807_aT();
	public void superFunc_174817_o(Object entity);
	public Object superFunc_174819_aU();
	public void superFunc_174834_g(Object nBTTagCompound);
	public boolean superFunc_174825_a(Object entityPlayer, Object vec3);
	public boolean superFunc_180427_aV();
	public void superFunc_174815_a(Object entityLivingBase, Object entity);
	public Object superGetEntityData();
	public boolean superShouldRiderSit();
	public Object superGetPickedResult(Object movingObjectPosition);
	public UUID superGetPersistentID();
	public boolean superShouldRenderInPass(int pass);
	public boolean superIsCreatureType(Object enumCreatureType, boolean forSpawnCount);
	public String superRegisterExtendedProperties(String identifier, Object iExtendedEntityProperties);
	public Object superGetExtendedProperties(String identifier);
	public boolean superCanRiderInteract();
	public boolean superShouldDismountInWater(Object entity);
	public boolean superHasHome();

}
