package modchu.lib;

import java.util.List;

public interface Modchu_IItemFood {
	public Object superSetMaxStackSize(int par1);
	public boolean superOnItemUse(Object itemStack, Object entityPlayer, Object world, Object blockPos, Object enumFacing, float f, float f1, float f2);
	public Object superOnItemRightClick(Object itemStack, Object world, Object entityPlayer);
	public Object superOnItemUseFinish(Object itemStack, Object world, Object entityPlayer);
	public int superGetItemStackLimit();
	public int superGetMetadata(int par1);
	public boolean superGetHasSubtypes();
	public Object superSetHasSubtypes(boolean par1);
	public int superGetMaxDamage();
	public Object superSetMaxDamage(int par1);
	public boolean superIsDamageable();
	public boolean superHitEntity(Object itemStack, Object entityLivingBase, Object entityLivingBase1);
	public boolean superItemInteractionForEntity(Object itemStack, Object entityPlayer, Object entityLivingBase);
	public Object superSetFull3D();
	public boolean superIsFull3D();
	public boolean superShouldRotateAroundWhenRendering();
	public Object superSetUnlocalizedName(String par1Str);
	public String superGetUnlocalizedNameInefficiently(Object itemStack);
	public String superGetUnlocalizedName();
	public String superGetUnlocalizedName(Object itemStack);
	public Object superSetContainerItem(Object item);
	public boolean superGetShareTag();
	public Object superGetContainerItem();
	public boolean superHasContainerItem();
	public int superGetColorFromItemStack(Object itemStack, int par2);
	public void superOnUpdate(Object itemStack, Object world, Object entity, int par4, boolean par5);
	public void superOnCreated(Object itemStack, Object world, Object entityPlayer);
	public boolean superIsMap();
	public Object superGetItemUseAction(Object itemStack);
	public int superGetMaxItemUseDuration(Object itemStack);
	public void superOnPlayerStoppedUsing(Object itemStack, Object world, Object entityPlayer, int par4);
	public Object superSetPotionEffect(String par1Str);
	public String superGetPotionEffect(Object itemStack);
	public boolean superIsPotionIngredient(Object itemStack);
	public void superAddInformation(Object itemStack, Object entityPlayer, List par3List, boolean par4);
	public String superGetItemStackDisplayName(Object itemStack);
	public boolean superHasEffect(Object itemStack);
	public Object superGetRarity(Object itemStack);
	public boolean superIsItemTool(Object itemStack);
	public Object superGetMovingObjectPositionFromPlayer(Object world, Object entityPlayer, boolean par3);
	public int superGetItemEnchantability();
	public Object superSetCreativeTab(Object creativeTabs);
	public Object superGetCreativeTab();
	public boolean superCanItemEditBlocks();
	public boolean superGetIsRepairable(Object itemStack, Object itemStack1);
	public Object superGetItemAttributeModifiers();
	public boolean superOnBlockDestroyed(Object itemStack, Object world, int par3, int par4, int par5, int par6, Object entityLivingBase);
	public String superGetStatName();
	public String superGetPotionEffect();
	public boolean superIsPotionIngredient();
	public String superGetItemDisplayName(Object itemStack);
	public Object superGetIconFromDamageForRenderPass(int par1, int par2);
	public boolean superOnItemUse(Object itemStack, Object entityPlayer, Object world, int par4, int par5, int par6, int par7, float par8, float par9, float par10);
	public void superGetSubItems(int par1, Object creativeTabs, List par3List);
	public void superRegisterIcons(Object iconRegister);
	public float superGetStrVsBlock(Object itemStack, Object block, int metadata);
	public void superOnUsingItemTick(Object itemStack, Object entityPlayer, int count);
	public Object superGetIcon(Object itemStack, int renderPass, Object entityPlayer, Object itemStack1, int useRemaining);
	public Object superGetContainerItemStack(Object itemStack);
	public Object superGetIcon(Object itemStack, int pass);
	public boolean superShouldPassSneakingClickToBlock(Object world, int par4, int par5, int par6);
	public void superOnArmorTickUpdate(Object world, Object entityPlayer, Object itemStack);
	public float superGetDamageVsEntity(Object entity, Object itemStack);
	public String superGetArmorTexture(Object itemStack, Object entity, int slot, int layer);
	public boolean superOnDroppedByPlayer(Object itemStack, Object entityPlayer);
	public boolean superOnItemUseFirst(Object itemStack, Object entityPlayer, Object world, Object blockPos, Object enumFacing, float hitX, float hitY, float hitZ);
	public boolean superIsRepairable();
	public Object superSetNoRepair();
	public boolean superOnLeftClickEntity(Object itemStack, Object entityPlayer, Object entity);
	public int superGetEntityLifespan(Object itemStack, Object world);
	public boolean superHasCustomEntity(Object itemStack);
	public Object superCreateEntity(Object world, Object entity, Object itemStack);
	public boolean superOnEntityItemUpdate(Object entityItem);
	public Object[] superGetCreativeTabs();
	public float superGetSmeltingExperience(Object itemStack);
	public Object superGetChestGenBase(Object chestGenHooks, Object random, Object weightedRandomChestContent);
	public boolean superIsValidArmor(Object itemStack, int armorType, Object entity);
	public boolean superIsBookEnchantable(Object itemStack, Object itemStack1);
	public String superGetArmorTexture(Object itemStack, Object entity, int slot, String type);
	public Object superGetFontRenderer(Object itemStack);
	public Object superGetArmorModel(Object entityLivingBase, Object itemStack, int armorSlot);
	public boolean superOnEntitySwing(Object entityLivingBase, Object itemStack);
	public void superRenderHelmetOverlay(Object itemStack, Object entityPlayer, Object scaledResolution, float partialTicks);
	public int superGetDamage(Object itemStack);
	public int superGetMetadata(Object itemStack);
	public int superGetMaxDamage(Object itemStack);
	public boolean superIsDamaged(Object itemStack);
	public void superSetDamage(Object itemStack, int damage);
	public boolean superCanHarvestBlock(Object block, Object itemStack);
	public int superGetItemStackLimit(Object itemStack);
	public float superGetStrVsBlock(Object itemStack, Object block);
	public boolean superOnBlockDestroyed(Object itemStack, Object world, Object block, Object blockPos, Object entityLivingBase);
	public boolean superCanHarvestBlock(Object block);
	public void superGetSubItems(Object item, Object creativeTabs, List p_150895_3_);
	public Object superGetAttributeModifiers(Object itemStack);
	public float superGetDigSpeed(Object itemStack, Object iBlockState);
	public void superOnUsingTick(Object itemStack, Object entityPlayer, int count);
	public Object superGetContainerItem(Object itemStack);
	public boolean superHasContainerItem(Object itemStack);
	public boolean superDoesSneakBypassUse(Object world, Object blockPos, Object entityPlayer);
	public void superOnArmorTick(Object world, Object entityPlayer, Object itemStack);
	public boolean superShowDurabilityBar(Object itemStack);
	public double superGetDurabilityForDisplay(Object itemStack);
	public void superSetHarvestLevel(String toolClass, int level);
	public Object superGetToolClasses(Object itemStack);
	public int superGetHarvestLevel(Object itemStack, String toolClass);
	public void superOnFoodEaten(Object itemStack, Object world, Object entityPlayer);
	public boolean superIsWolfsFavoriteMeat();
	public Object superSetPotionEffect(int par1, int par2, int par3, float par4);
	public Object superSetAlwaysEdible();
	public boolean superUpdateItemStackNBT(Object nBTTagCompound);
	public boolean superOnBlockStartBreak(Object itemStack, Object blockPos, Object entityPlayer);
	public Object superGetModel(Object itemStack, Object entityPlayer, int useRemaining);
	public int superGetItemEnchantability(Object itemStack);
	public boolean superIsBeaconPayment(Object itemStack);
	public int superGetHealAmount(Object itemStack);
	public float superGetSaturationModifier(Object itemStack);
	public int superGetSpriteNumber();
	public Object superGetIconFromDamage(int par1);
	public Object superGetIconIndex(Object itemStack);
	public boolean superDoesContainerItemLeaveCraftingGrid(Object itemStack);
	public boolean superRequiresMultipleRenderPasses();
	public Object superSetTextureName(String par1Str);
	public String superGetIconString();
	public boolean superOnItemUseFirst(Object itemStack, Object entityPlayer, Object world, int x, int y, int z, int side, float hitX, float hitY, float hitZ);
	public boolean superOnBlockStartBreak(Object itemStack, int X, int Y, int Z, Object entityPlayer);
	public int superGetRenderPasses(int metadata);
	public void superRenderHelmetOverlay(Object itemStack, Object entityPlayer, Object scaledResolution, float partialTicks, boolean hasScreen, int mouseX, int mouseY);
	public int superGetDisplayDamage(Object itemStack);
	public boolean superHasEffect(Object itemStack, int pass);
	public boolean superOnBlockDestroyed(Object itemStack, Object world, Object block, int p_150894_4_, int p_150894_5_, int p_150894_6_, Object entityLivingBase);
	public float superGetDigSpeed(Object itemStack, Object block, int metadata);
	public boolean superDoesSneakBypassUse(Object world, int x, int y, int z, Object entityPlayer);

}
