package modchu.lib;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

public interface Modchu_IBlock {
	public void superInitializeBlock();
	public Object superSetSoundType(Object stepSound);
	public Object superSetLightOpacity(int par1);
	public Object superSetLightLevel(float par1);
	public Object superSetResistance(float par1);
	public boolean superIsFullCube();
	public boolean superIsPassable(Object iBlockAccess, int par2, int par3, int par4);
	public int superGetRenderType();
	public Object superSetHardness(float par1);
	public Object superSetBlockUnbreakable();
	public float superGetBlockHardness(Object world, int par2, int par3, int par4);
	public Object superSetTickRandomly(boolean par1);
	public boolean superGetTickRandomly();
	public boolean superHasTileEntity();
	public float superGetBlockBrightness(Object iBlockAccess, int par2, int par3, int par4);
	public int superGetPackedLightmapCoords(Object iBlockAccess, int par2, int par3, int par4);
	public boolean superShouldSideBeRendered(Object iBlockAccess, int par2, int par3, int par4, int par5);
	public boolean superIsBlockSolid(Object iBlockAccess, int par2, int par3, int par4, int par5);
	public Object superGetBlockTexture(Object iBlockAccess, int par2, int par3, int par4, int par5);
	public Object superGetIcon(int par1, int par2);
	public void superAddCollisionBoxesToList(Object world, int par2, int par3, int par4, Object axisAlignedBB, List par6List, Object entity);
	public Object superGetCollisionBoundingBox(Object world, int par2, int par3, int par4);
	public Object superGetCollisionBoundingBoxFromPool(Object world, int par2, int par3, int par4);
	public boolean superIsOpaqueCube();
	public boolean superCanCollideCheck(Object par1, boolean par2);
	public boolean superIsCollidable();
	public void superUpdateTick(Object world, int par2, int par3, int par4, Random par5Random);
	public void superRandomDisplayTick(Object world, int par2, int par3, int par4, Random par5Random);
	public void superOnBlockDestroyedByPlayer(Object world, int par2, int par3, int par4, int par5);
	public void superNeighborChanged(Object world, int par2, int par3, int par4, Object par5);
	public int superTickRate(Object world);
	public void superOnBlockAdded(Object world, int par2, int par3, int par4);
	public void superBreakBlock(Object world, int par2, int par3, int par4, Object par5, int par6);
	public int superQuantityDropped(Random par1Random);
	public Object superGetItemDropped(int par1, Random par2Random, int par3);
	public float superGetPlayerRelativeBlockHardness(Object entityPlayer, Object world, int par3, int par4, int par5);
	public void superDropBlockAsItemWithChance(Object world, int par2, int par3, int par4, int par5, float par6, int par7);
	public void superDropBlockAsItem(Object world, int par2, int par3, int par4, Object itemStack);
	public void superDropXpOnBlockBreak(Object world, int par2, int par3, int par4, int par5);
	public int superDamageDropped(int par1);
	public float superGetExplosionResistance(Object entity);
	public Object superCollisionRayTrace(Object world, int par2, int par3, int par4, Object vec3, Object vec31);
	public void superOnBlockDestroyedByExplosion(Object world, int par2, int par3, int par4, Object explosion);
	public boolean superCanReplace(Object world, int par2, int par3, int par4, int par5, Object itemStack);
	public int superGetRenderBlockPass();
	public boolean superCanPlaceBlockOnSide(Object world, int par2, int par3, int par4, int par5);
	public boolean superCanPlaceBlockAt(Object world, int par2, int par3, int par4);
	public boolean superOnBlockActivated(Object world, int par2, int par3, int par4, Object entityPlayer, int par6, float par7, float par8, float par9);
	public void superOnEntityWalking(Object world, int par2, int par3, int par4, Object entity);
	public int superOnBlockPlaced(Object world, int par2, int par3, int par4, int par5, float par6, float par7, float par8, int par9);
	public void superOnBlockClicked(Object world, int par2, int par3, int par4, Object entityPlayer);
	public void superVelocityToAddToEntity(Object world, int par2, int par3, int par4, Object entity, Object vec3);
	public void superSetBlockBoundsBasedOnState(Object iBlockAccess, int par2, int par3, int par4);
	public int superGetBlockColor();
	public int superGetRenderColor(int par1);
	public int superGetWeakPower(Object iBlockAccess, int par2, int par3, int par4, int par5);
	public int superColorMultiplier(Object iBlockAccess, int par2, int par3, int par4);
	public boolean superCanProvidePower();
	public void superOnEntityWalk(Object world, int par2, int par3, int par4, Object entity);
	public int superGetStrongPower(Object iBlockAccess, int par2, int par3, int par4, int par5);
	public void superSetBlockBoundsForItemRender();
	public void superHarvestBlock(Object world, Object entityPlayer, int par3, int par4, int par5, int par6);
	public boolean superCanSilkHarvest();
	public Object superCreateStackedBlock(int par1);
	public int superQuantityDroppedWithBonus(int par1, Random par2Random);
	public boolean superCanBlockStay(Object world, int par2, int par3, int par4);
	public void superOnBlockPlacedBy(Object world, int par2, int par3, int par4, Object entityLivingBase, Object itemStack);
	public void superOnPostBlockPlaced(Object world, int par2, int par3, int par4, int par5);
	public Object superSetUnlocalizedName(String par1Str);
	public String superGetLocalizedName();
	public String superGetUnlocalizedName();
	public boolean superEventReceived(Object world, int par2, int par3, int par4, int par5, int par6);
	public boolean superGetEnableStats();
	public Object superDisableStats();
	public int superGetMobilityFlag();
	public float superGetAmbientOcclusionLightValue(Object iBlockAccess, int par2, int par3, int par4);
	public void superOnFallenUpon(Object world, int par2, int par3, int par4, Object entity, float par6);
	public Object superGetItem(Object world, int par2, int par3, int par4);
	public int superGetDamageValue(Object world, int par2, int par3, int par4);
	public void superGetSubBlocks(Object par1, Object creativeTabs, Object par3List);
	public Object superSetCreativeTab(Object creativeTabs);
	public void superOnBlockHarvested(Object world, int par2, int par3, int par4, int par5, Object entityPlayer);
	public Object superGetCreativeTabToDisplayOn();
	public void superOnBlockPreDestroy(Object world, int par2, int par3, int par4, int par5);
	public void superFillWithRain(Object world, int par2, int par3, int par4);
	public boolean superIsFlowerPot();
	public boolean superRequiresUpdates();
	public boolean superCanDropFromExplosion(Object explosion);
	public boolean superIsAssociatedBlock(Object par1);
	public boolean superHasComparatorInputOverride();
	public int superGetComparatorInputOverride(Object world, int par2, int par3, int par4, int par5);
	public Object superSetBlockTextureName(String par1Str);
	public String superGetTextureName();
	public void superRegisterIcons(Object iconRegister);
	public String superGetItemIconName();
	public int superGetLightValue(Object iBlockAccess, int x, int y, int z);
	public boolean superIsLadder(Object world, int x, int y, int z, Object entityLivingBase);
	public boolean superIsNormalCube(Object world, int x, int y, int z);
	public boolean superIsSideSolid(Object world, int x, int y, int z, Object forgeDirection);
	public boolean superIsReplaceable(Object world, int x, int y, int z);
	public boolean superIsBurning(Object world, int x, int y, int z);
	public boolean superIsAir(Object world, int x, int y, int z);
	public boolean superCanHarvestBlock(Object entityPlayer, int meta);
	public boolean superRemovedByPlayer(Object world, Object entityPlayer, int x, int y, int z);
	public void superAddCreativeItems(ArrayList itemList);
	public int superGetFlammability(Object iBlockAccess, int x, int y, int z, int metadata, Object forgeDirection);
	public boolean superIsFlammable(Object iBlockAccess, int x, int y, int z, int metadata, Object forgeDirection);
	public int superGetFireSpreadSpeed(Object world, int x, int y, int z, int metadata, Object forgeDirection);
	public boolean superIsFireSource(Object world, int x, int y, int z, int metadata, Object forgeDirection);
	public boolean superHasTileEntity(int metadata);
	public Object superCreateTileEntity(Object world, int metadata);
	public int superQuantityDropped(int meta, int fortune, Random random);
	public Object superGetDrops(Object world, int x, int y, int z, int metadata, int fortune);
	public boolean superCanSilkHarvest(Object world, Object entityPlayer, int x, int y, int z, int metadata);
	public boolean superCanCreatureSpawn(Object enumCreatureType, Object world, int x, int y, int z);
	public boolean superIsBed(Object world, int x, int y, int z, Object entityLivingBase);
	public Object superGetBedSpawnPosition(Object world, int x, int y, int z, Object entityPlayer);
	public void superSetBedOccupied(Object world, int x, int y, int z, Object entityPlayer, boolean occupied);
	public int superGetBedDirection(Object iBlockAccess, int x, int y, int z);
	public boolean superIsBedFoot(Object iBlockAccess, int x, int y, int z);
	public void superBeginLeavesDecay(Object world, int x, int y, int z);
	public boolean superCanSustainLeaves(Object world, int x, int y, int z);
	public boolean superIsLeaves(Object world, int x, int y, int z);
	public boolean superCanBeReplacedByLeaves(Object world, int x, int y, int z);
	public boolean superIsWood(Object world, int x, int y, int z);
	public boolean superIsReplaceableOreGen(Object world, int x, int y, int z, Object target);
	public float superGetExplosionResistance(Object entity, Object world, int x, int y, int z, double explosionX, double explosionY, double explosionZ);
	public void superOnBlockExploded(Object world, int x, int y, int z, Object explosion);
	public boolean superCanConnectRedstone(Object iBlockAccess, int x, int y, int z, int side);
	public boolean superCanPlaceTorchOnTop(Object world, int x, int y, int z);
	public boolean superCanRenderInPass(int pass);
	public Object superGetPickBlock(Object movingObjectPosition, Object world, int x, int y, int z);
	public boolean superIsFoliage(Object world, int x, int y, int z);
	public boolean superAddHitEffects(Object world, Object movingObjectPosition, Object effectRenderer);
	public boolean superAddDestroyEffects(Object world, int x, int y, int z, int meta, Object effectRenderer);
	public boolean superCanSustainPlant(Object world, int x, int y, int z, Object forgeDirection, Object iPlantable);
	public void superOnPlantGrow(Object world, int x, int y, int z, int sourceX, int sourceY, int sourceZ);
	public boolean superIsFertile(Object world, int x, int y, int z);
	public int superGetLightOpacity(Object world, int x, int y, int z);
	public boolean superCanEntityDestroy(Object world, int x, int y, int z, Object entity);
	public boolean superCanDragonDestroy(Object world, int x, int y, int z);
	public boolean superIsBeaconBase(Object world, int x, int y, int z, int beaconX, int beaconY, int beaconZ);
	public boolean superRotateBlock(Object world, int x, int y, int z, Object forgeDirection);
	public Object[] superGetValidRotations(Object world, int x, int y, int z);
	public float superGetEnchantPowerBonus(Object world, int x, int y, int z);
	public boolean superRecolourBlock(Object world, int x, int y, int z, Object forgeDirection, int colour);
	public int superGetExpDrop(Object world, int data, int enchantmentLevel);
	public void superOnNeighborChange(Object world, int x, int y, int z, int tileX, int tileY, int tileZ);
	public boolean superWeakTileChanges();
	public boolean superShouldCheckWeakPower(Object world, int x, int y, int z, int side);
	public float superGetFilledPercentage(Object world, int x, int y, int z);
	// 172~
	public float superGetAmbientOcclusionLightValue();
	public int superGetFlammability(Object iBlockAccess, int x, int y, int z, Object forgeDirection);
	public boolean superIsFlammable(Object iBlockAccess, int x, int y, int z, Object forgeDirection);
	public int superGetFireSpreadSpeed(Object world, int x, int y, int z, Object forgeDirection);
	public boolean superIsFireSource(Object world, int x, int y, int z, Object forgeDirection);
	// 180~
	public boolean superCanEntityDestroy(Object world, Object pos, Object entity);
	public boolean superIsPassable(Object iBlockAccess, Object blockPos);
	public float superGetBlockHardness(Object world, Object blockPos);
	public int superGetPackedLightmapCoords(Object iBlockAccess, Object blockPos);
	public boolean superShouldSideBeRendered(Object iBlockAccess, Object blockPos, Object side);
	public boolean superIsBlockSolid(Object iBlockAccess, Object blockPos, Object enumFacing);
	public void superAddCollisionBoxesToList(Object world, Object blockPos, Object iBlockState, Object axisAlignedBB, List list, Object entity);
	public Object getCollisionBoundingBox(Object iBlockState, Object world, Object blockPos);
	public Object superGetCollisionBoundingBox(Object world, Object blockPos, Object iBlockState);
	public void superUpdateTick(Object world, Object blockPos, Object iBlockState, Random par5Random);
	public void superRandomDisplayTick(Object iBlockState, Object world, Object blockPos, Random par5Random);
	public void superOnBlockDestroyedByPlayer(Object world, Object blockPos, Object iBlockState);
	public void superOnBlockAdded(Object world, Object blockPos, Object iBlockState);
	public float superGetPlayerRelativeBlockHardness(Object entityPlayer, Object world, Object blockPos);
	public void superDropBlockAsItemWithChance(Object world, Object blockPos, Object iBlockState, float par6, int par7);
	public void superOnEntityWalk(Object world, Object blockPos, Object entity);
	public boolean superIsFullBlock();
	public int superGetLightOpacity();
	public boolean superIsTranslucent();
	public int superGetLightValue();
	public boolean superGetUseNeighborBrightness();
	public Object superGetMaterial();
	public Object superGetMapColor(Object iBlockState);
	public Object superGetStateFromMeta(int meta);
	public int superGetMetaFromState(Object iBlockState);
	public Object superGetActualState(Object iBlockState, Object iBlockAccess, Object blockPos);
	public boolean superIsNormalCube();
	public boolean superIsVisuallyOpaque(Object iBlockState);
	public boolean superIsReplaceable(Object world, Object blockPos);
	public Object superGetSelectedBoundingBox(Object world, Object blockPos);
	public void superRandomTick(Object world, Object blockPos, Object iBlockState, Random random);
	public void superNeighborChanged(Object iBlockState, Object world, Object blockPos, Object block, Object blockPos1);
	public void superBreakBlock(Object world, Object blockPos, Object iBlockState);
	public Object superGetItemDropped(Object iBlockState, Random rand, int fortune);
	public void superDropXpOnBlockBreak(Object world, Object blockPos, int amount);
	public int superDamageDropped(Object iBlockState);
	public Object superCollisionRayTrace(Object world, Object blockPos, Object vec3, Object vec31);
	public void superOnBlockDestroyedByExplosion(Object world, Object blockPos, Object explosion);
	public boolean superCanReplace(Object world, Object blockPos, Object enumFacing, Object itemStack);
	public boolean superCanPlaceBlockOnSide(Object world, Object blockPos, Object enumFacing);
	public Object superGetBlockLayer();
	public boolean superCanPlaceBlockAt(Object world, Object blockPos);
	public boolean superOnBlockActivated(Object world, Object blockPos, Object iBlockState, Object entityPlayer, Object enumFacing, float hitX, float hitY, float hitZ);
	public Object superOnBlockPlaced(Object world, Object blockPos, Object enumFacing, float hitX, float hitY, float hitZ, int meta, Object entityLivingBase);
	public void superOnBlockClicked(Object world, Object blockPos, Object entityPlayer);
	public Object superModifyAcceleration(Object world, Object blockPos, Object entity, Object vec3);
	public void superSetBlockBoundsBasedOnState(Object iBlockAccess, Object blockPos);
	public int superGetRenderColor(Object iBlockState);
	public int superColorMultiplier(Object iBlockAccess, Object blockPos, int renderPass);
	public int superGetWeakPower(Object iBlockAccess, Object blockPos, Object iBlockState, Object enumFacing);
	public void superOnEntityWalk(Object world, Object blockPos, Object iBlockState, Object entity);
	public int superGetStrongPower(Object iBlockState, Object iBlockAccess, Object blockPos, Object enumFacing);
	public void superHarvestBlock(Object world, Object entityPlayer, Object blockPos, Object iBlockState, Object tileEntity);
	public Object superCreateStackedBlock(Object iBlockState);
	public void superOnBlockPlacedBy(Object world, Object blockPos, Object iBlockState, Object entityLivingBase, Object itemStack);
	public boolean superEventReceived(Object world, Object blockPos, Object iBlockState, int eventID, int eventParam);
	public void superOnFallenUpon(Object world, Object blockPos, Object entity, float fallDistance);
	public void superOnLanded(Object world, Object entity);
	public Object superGetItem(Object world, Object blockPos);
	public int superGetDamageValue(Object world, Object blockPos);
	public void superOnBlockHarvested(Object world, Object blockPos, Object iBlockState, Object entityPlayer);
	public void superFillWithRain(Object world, Object blockPos);
	public int superGetComparatorInputOverride(Object world, Object blockPos);
	public Object superGetStateForEntityRender(Object iBlockState);
	public Object superCreateBlockState();
	public Object superGetBlockState();
	public Object superGetOffsetType();
	public int superGetLightValue(Object iBlockAccess, Object blockPos);
	public boolean superIsLadder(Object iBlockAccess, Object blockPos, Object entityLivingBase);
	public boolean superIsNormalCube(Object iBlockAccess, Object blockPos);
	public boolean superIsSideSolid(Object iBlockAccess, Object blockPos, Object enumFacing);
	public boolean superIsBurning(Object iBlockAccess, Object blockPos);
	public boolean superIsAir(Object iBlockAccess, Object blockPos);
	public boolean superCanHarvestBlock(Object iBlockAccess, Object blockPos, Object entityPlayer);
	public boolean superRemovedByPlayer(Object world, Object blockPos, Object entityPlayer, boolean willHarvest);
	public int superGetFlammability(Object iBlockAccess, Object blockPos, Object enumFacing);
	public boolean superIsFlammable(Object iBlockAccess, Object blockPos, Object enumFacing);
	public int superGetFireSpreadSpeed(Object iBlockAccess, Object blockPos, Object enumFacing);
	public boolean superIsFireSource(Object world, Object blockPos, Object enumFacing);
	public boolean superHasTileEntity(Object iBlockState);
	public Object superCreateTileEntity(Object world, Object iBlockState);
	public int superQuantityDropped(Object iBlockState, int fortune, Random random);
	public Object superGetDrops(Object iBlockAccess, Object blockPos, Object iBlockState, int fortune);
	public boolean superCanSilkHarvest(Object world, Object blockPos, Object iBlockState, Object entityPlayer);
	public boolean superCanCreatureSpawn(Object iBlockAccess, Object blockPos, Object spawnPlacementType);
	public boolean superIsBed(Object iBlockAccess, Object blockPos, Object entity);
	public Object superGetBedSpawnPosition(Object iBlockAccess, Object blockPos, Object entityPlayer);
	public void superSetBedOccupied(Object iBlockAccess, Object blockPos, Object entityPlayer, boolean occupied);
	public Object superGetBedDirection(Object iBlockAccess, Object blockPos);
	public boolean superIsBedFoot(Object iBlockAccess, Object blockPos);
	public void superBeginLeavesDecay(Object world, Object blockPos);
	public boolean superCanSustainLeaves(Object iBlockAccess, Object blockPos);
	public boolean superIsLeaves(Object iBlockAccess, Object blockPos);
	public boolean superCanBeReplacedByLeaves(Object iBlockAccess, Object blockPos);
	public boolean superIsWood(Object iBlockAccess, Object blockPos);
	public boolean superIsReplaceableOreGen(Object world, Object blockPos, Object predicate);
	public float superGetExplosionResistance(Object world, Object blockPos, Object entity, Object explosion);
	public void superOnBlockExploded(Object world, Object blockPos, Object explosion);
	public boolean superCanConnectRedstone(Object iBlockAccess, Object blockPos, Object enumFacing);
	public boolean superCanPlaceTorchOnTop(Object iBlockAccess, Object blockPos);
	public Object superGetPickBlock(Object movingObjectPosition, Object world, Object blockPos);
	public boolean superIsFoliage(Object iBlockAccess, Object blockPos);
	public boolean superAddDestroyEffects(Object world, Object blockPos, Object effectRenderer);
	public boolean superCanSustainPlant(Object iBlockAccess, Object blockPos, Object enumFacing, Object iPlantable);
	public void superOnPlantGrow(Object world, Object blockPos, Object blockPos1);
	public boolean superIsFertile(Object world, Object blockPos);
	public int superGetLightOpacity(Object iBlockAccess, Object blockPos);
	public boolean superIsBeaconBase(Object iBlockAccess, Object blockPos, Object blockPos1);
	public boolean superRotateBlock(Object world, Object blockPos, Object enumFacing);
	public Object[] superGetValidRotations(Object world, Object blockPos);
	public float superGetEnchantPowerBonus(Object world, Object blockPos);
	public boolean superRecolorBlock(Object world, Object blockPos, Object enumFacing, Object enumDyeColor);
	public int superGetExpDrop(Object iBlockAccess, Object blockPos, int fortune);
	public void superOnNeighborChange(Object iBlockAccess, Object blockPos, Object blockPos1);
	public boolean superShouldCheckWeakPower(Object iBlockAccess, Object blockPos, Object enumFacing);
	public boolean superGetWeakChanges(Object iBlockAccess, Object blockPos);
	public void superSetHarvestLevel(String toolClass, int level);
	public void superSetHarvestLevel(String toolClass, int level, Object iBlockState);
	public String superGetHarvestTool(Object iBlockState);
	public int superGetHarvestLevel(Object iBlockState);
	public boolean superIsToolEffective(String type, Object iBlockState);
	public Object superGetExtendedState(Object iBlockState, Object iBlockAccess, Object blockPos);
	public boolean superCanRenderInLayer(Object enumWorldBlockLayer);
	public Object superCaptureDrops(boolean start);
	// ~152
	public String superGetUnlocalizedName2();
	public void superOnSetBlockIDWithMetaData(Object world, int par2, int par3, int par4, int par5);
	public boolean superIsLadder(Object world, int x, int y, int z);
	public int superGetEnchantPower(Object world, int x, int y, int z);
	// 190~
	public boolean superIsNormalCube(Object iBlockState);
	public Object superGetRenderType(Object iBlockState);
	public boolean superIsOpaqueCube(Object iBlockState);
	public boolean superCanProvidePower(Object iBlockState);
	public Object superGetMobilityFlag(Object iBlockState);
	public boolean superHasComparatorInputOverride(Object iBlockState);
	public float superGetAmbientOcclusionLightValue(Object iBlockState);
	public boolean superAddHitEffects(Object iBlockState, Object world, Object rayTraceResult, Object effectRenderer);
	public float superGetBlockHardness(Object iBlockState, Object world, Object blockPos);
	public int superGetPackedLightmapCoords(Object iBlockStatem, Object iBlockAccess, Object blockPos);
	public boolean superShouldSideBeRendered(Object iBlockState, Object iBlockAccess, Object blockPos, Object enumFacing);
	public float superGetPlayerRelativeBlockHardness(Object iBlockState, Object entityPlayer, Object world, Object blockPos);
	public boolean superIsFullBlock(Object iBlockState);
	public int superGetLightOpacity(Object iBlockState);
	public boolean superIsTranslucent(Object iBlockState);
	public int superGetLightValue(Object iBlockState);
	public boolean superGetUseNeighborBrightness(Object iBlockState);
	public Object superGetMaterial(Object iBlockState);
	public Object superGetSelectedBoundingBox(Object iBlockState, Object world, Object blockPos);
	public Object superCollisionRayTrace(Object iBlockState, Object world, Object blockPos, Object vec3, Object vec31);
	public boolean superOnBlockActivated(Object world, Object blockPos, Object iBlockState, Object entityPlayer, Object enumHand, Object itemStack, Object enumFacing, float hitX, float hitY, float hitZ);
	public void superHarvestBlock(Object world, Object entityPlayer, Object blockPos, Object iBlockState, Object tileEntity, Object itemStack);
	public Object superGetItem(Object world, Object blockPos, Object iBlockState);
	public int superGetComparatorInputOverride(Object iBlockState, Object world, Object blockPos);
	public int superGetLightValue(Object iBlockState, Object iBlockAccess, Object blockPos);
	public boolean superIsLadder(Object iBlockState, Object iBlockAccess, Object blockPos, Object entityLivingBase);
	public boolean superIsNormalCube(Object iBlockState, Object iBlockAccess, Object blockPos);
	public boolean superIsSideSolid(Object iBlockState, Object iBlockAccess, Object blockPos, Object enumFacing);
	boolean superIsAir(Object iBlockState, Object iBlockAccess, Object blockPos);
	boolean superRemovedByPlayer(Object iBlockState, Object world, Object blockPos, Object entityPlayer, boolean willHarvest);
	boolean superCanCreatureSpawn(Object iBlockState, Object iBlockAccess, Object blockPos, Object spawnPlacementType);
	boolean superIsBed(Object iBlockState, Object iBlockAccess, Object blockPos, Object entity);
	Object superGetBedSpawnPosition(Object iBlockState, Object iBlockAccess, Object blockPos, Object entityPlayer);
	Object superGetBedDirection(Object iBlockState, Object iBlockAccess, Object blockPos);
	void superBeginLeavesDecay(Object iBlockState, Object world, Object blockPos);
	boolean superCanSustainLeaves(Object iBlockState, Object iBlockAccess, Object blockPos);
	boolean superIsLeaves(Object iBlockState, Object iBlockAccess, Object blockPos);
	boolean superCanBeReplacedByLeaves(Object iBlockState, Object iBlockAccess, Object blockPos);
	boolean superIsReplaceableOreGen(Object iBlockState, Object iBlockAccess, Object blockPos, Object predicate);
	boolean superCanConnectRedstone(Object iBlockState, Object iBlockAccess, Object blockPos, Object enumFacing);
	boolean superCanPlaceTorchOnTop(Object iBlockState, Object iBlockAccess, Object blockPos);
	Object superGetPickBlock(Object iBlockState, Object movingObjectPosition, Object world, Object blockPos, Object entityPlayer);
	boolean superCanSustainPlant(Object iBlockState, Object iBlockAccess, Object blockPos, Object enumFacing, Object iPlantable);
	void superOnPlantGrow(Object iBlockState, Object world, Object blockPos, Object blockPos1);
	int superGetLightOpacity(Object iBlockState, Object iBlockAccess, Object blockPos);
	boolean superCanEntityDestroy(Object iBlockState, Object iBlockAccess, Object blockPos, Object entity);
	int superGetExpDrop(Object iBlockState, Object iBlockAccess, Object blockPos, int fortune);
	boolean superShouldCheckWeakPower(Object iBlockState, Object iBlockAccess, Object blockPos, Object enumFacing);
	boolean superIsFullCube(Object iBlockState);
	public boolean superIsFullyOpaque(Object iBlockState);
	public Object superWithRotation(Object iBlockState, Object rotation);
	public Object superWithMirror(Object iBlockState, Object mirror);
	public Object superGetBoundingBox(Object iBlockState, Object iBlockAccess, Object blockPos);
	public void superAddCollisionBoxToList(Object iBlockState, Object world, Object blockPos, Object axisAlignedBB, Object p_185477_5_, Object entity);
	public Object superRayTrace(Object blockPos, Object vec3d, Object vec3d1, Object axisAlignedBB);
	public boolean superCanSpawnInBlock();
	public Object superGetSoundType();
	public String superToString();
	public boolean superDoesSideBlockRendering(Object iBlockState, Object iBlockAccess, Object blockPos, Object enumFacing);
	public boolean superAddLandingEffects(Object iBlockState, Object worldServer, Object blockPos, Object iBlockState1, Object entityLivingBase, int numberOfParticles);
	public Object superIsEntityInsideMaterial(Object iBlockAccess, Object blockPos, Object iBlockState, Object entity, double yToTest, Object material, boolean testingHead);
	public Object superIsAABBInsideMaterial(Object world, Object blockPos, Object axisAlignedBB, Object material);
	public void superEventReceived(Object world, int par2, int par3, int par4, Object par5);
	public boolean superNeighborChanged(Object world, int par2, int par3, int par4, int par5, int par6);

}
