package modchu.lib;

import java.util.Random;
import java.util.UUID;

public interface Modchu_IEntityOtherPlayerMPMaster {
	public void updateCloak();
	public void sendChatToPlayer(String par1Str);
	public int getMaxHealth();
	public boolean func_96122_a(Object entityPlayer);
	public void alertWolves(Object entityLiving, boolean par2);
	public void damageArmor(int par1);
	public float func_82243_bO();
	public boolean func_71066_bF();
	public void func_82162_bC();
	public boolean canCurrentToolHarvestBlock(int par1, int par2, int par3);
	public boolean func_94062_bN();
	public boolean func_94059_bO();
	public boolean canPickUpLoot();
	public Object getTranslator();
	public String translateString(String par1Str, Object... par2ArrayOfObj);
	public boolean func_98034_c(Object entityPlayer);
	public boolean func_96092_aw();
	public int func_96121_ay();
	public Object getLookHelper();
	public Object getMoveHelper();
	public Object getJumpHelper();
	public Object getNavigator();
	public Object getEntitySenses();
	public Object getAttackTarget();
	public void setAttackTarget(Object entityLiving);
	public boolean canAttackClass(Class par1Class);
	public void eatGrassBonus();
	public boolean isWithinHomeDistanceCurrentPosition();
	public boolean isWithinHomeDistance(int par1, int par2, int par3);
	public void setHomeArea(int par1, int par2, int par3, int par4);
	public Object getHomePosition();
	public float getMaximumHomeDistance();
	public void detachHome();
	public boolean hasHome();
	public String getTexture();
	public int getTalkInterval();
	public void playLivingSound();
	public void spawnExplosionParticle();
	public int getHealthInt();
	public String getLivingSound();
	public int getDropItemId();
	public void setMoveForward(float par1);
	public void func_85033_bc();
	public boolean canDespawn();
	public void despawnEntity();
	public int getVerticalFaceSpeed();
	public void faceEntity(Object entity, float par2, float par3);
	public boolean getCanSpawnHere();
	public float getRenderSizeModifier();
	public int getMaxSpawnedInChunk();
	public float getSpeedModifier();
	public int func_82143_as();
	public void initCreature();
	public boolean canBeSteered();
	public void func_94058_c(String par1Str);
	public String func_94057_bL();
	public boolean func_94056_bM();
	public void func_94061_f(boolean par1);
	public void func_96120_a(int par1, float par2);
	public void setCanPickUpLoot(boolean par1);
	public boolean func_104002_bU();
	public boolean addNotRiddenEntityID(Object nBTTagCompound);
	public boolean addEntityID(Object nBTTagCompound);
	public boolean interact(Object entityPlayer);
	public void unmountEntity(Object entity);
	public boolean func_85031_j(Object entity);
	public void func_82149_j(Object entity);
	public float func_82146_a(Object explosion, Object world, int par3, int par4, int par5, Object block);
	public boolean func_96091_a(Object explosion, Object world, int par3, int par4, int par5, int par6, float par7);
	public void func_85029_a(Object crashReportCategory);


	public void sendChatToPlayer(Object chatMessageComponent);
	public void setupCustomSkin();
	public Object getTextureSkin();
	public Object getTextureCape();
	public Object dropPlayerItem(Object itemStack);
	public float getCurrentPlayerStrVsBlock(Object block, boolean par2, int meta);
	public void displayGUIHopper(Object tileEntityHopper);
	public void displayGUIFurnace(Object tileEntityFurnace);
	public void displayGUIDispenser(Object tileEntityDispenser);
	public void displayGUIEditSign(Object tileEntity);
	public void displayGUIBrewingStand(Object tileEntityBrewingStand);
	public void displayGUIBeacon(Object tileEntityBeacon);
	public void addChatMessage(String par1Str);
	public String getEntityName();
	public Object getCurrentItemOrArmor(int par1);
	public String getTranslatedEntityName();
	public void playStepSound(int par1, int par2, int par3, int par4);
	public boolean isInRangeToRenderVec3D(Object vec3);
	public Object dropItem(int par1, int par2);
	public Object dropItemWithOffset(int par1, int par2, float par3);
	public float getBlockExplosionResistance(Object explosion, Object world, int par3, int par4, int par5, Object block);
	public boolean shouldExplodeBlock(Object explosion, Object world, int par3, int par4, int par5, int par6, float par7);


	public void setPositionAndRotation2(double p_70056_1_, double p_70056_3_, double p_70056_5_, float p_70056_7_, float p_70056_8_, int p_70056_9_);
	public float getShadowSize();
	public boolean canCommandSenderUseCommand(int p_70003_1_, String p_70003_2_);
	public Object getPlayerCoordinates();
	public boolean func_152122_n();
	public boolean func_152123_o();
	public void func_152121_a(Object type, Object resourceLocation);
	public Object func_146097_a(Object itemStack, boolean p_146097_2_, boolean p_146097_3_);
	public float getCurrentPlayerStrVsBlock(Object block, boolean p_146096_2_);
	public float getBreakSpeed(Object block, boolean p_146096_2_, int meta);
	public float getBreakSpeed(Object block, boolean p_146096_2_, int meta, int x, int y, int z);
	public void func_146093_a(Object tileEntityHopper);
	public void displayGUIHopperMinecart(Object entityMinecartHopper);
	public void displayGUIEnchantment(int p_71002_1_, int p_71002_2_, int p_71002_3_, String p_71002_4_);
	public void displayGUIAnvil(int p_82244_1_, int p_82244_2_, int p_82244_3_);
	public void displayGUIWorkbench(int p_71058_1_, int p_71058_2_, int p_71058_3_);
	public void func_146101_a(Object tileEntityFurnace);
	public void func_146102_a(Object tileEntityDispenser);
	public void func_146100_a(Object tileEntity);
	public void func_146095_a(Object commandBlockLogic);
	public void func_146098_a(Object tileEntityBrewingStand);
	public void func_146104_a(Object tileEntityBeacon);
	public void displayGUIMerchant(Object iMerchant, String p_71030_2_);
	public Object sleepInBedAt(int p_71018_1_, int p_71018_2_, int p_71018_3_);
	public boolean getHideCape(int p_82241_1_);
	public void setHideCape(int p_82239_1_, boolean p_82239_2_);
	public void setSpawnChunk(Object chunkCoordinates, boolean p_71063_2_);
	public void fall(float p_70069_1_);
	public String func_146067_o(int p_146067_1_);
	public Object getItemIcon(Object itemStack, int p_70620_2_);
	public boolean isCurrentToolAdventureModeExempt(int p_82246_1_, int p_82246_2_, int p_82246_3_);
	public boolean canPlayerEdit(int p_82247_1_, int p_82247_2_, int p_82247_3_, int p_82247_4_, Object itemStack);
	public String getName();
	public Object[] getLastActiveItems();
	public boolean getHideCape();
	public Object func_145748_c_();
	public Object getPosition(float par1);
	public void updateFallState(double p_70064_1_, boolean p_70064_3_);
	public int func_142015_aE();
	public void dropRareDrop(int p_70600_1_);
	public Object func_110142_aN();
	public boolean isAIEnabled();
	public void updateAITasks();
	public boolean isClientWorld();
	public void func_145775_I();
	public void func_145780_a(int p_145780_1_, int p_145780_2_, int p_145780_3_, Object block);
	public boolean handleLavaMovement();
	public Object func_145778_a(Object item, int p_145778_2_, float p_145778_3_);
	public boolean func_145771_j(double p_145771_1_, double p_145771_3_, double p_145771_5_);
	public boolean isEntityInvulnerable();
	public void copyDataFrom(Object entity, boolean p_82141_2_);
	public float func_145772_a(Object explosion, Object world, int p_145772_3_, int p_145772_4_, int p_145772_5_, Object block);
	public boolean func_145774_a(Object explosion, Object world, int p_145774_3_, int p_145774_4_, int p_145774_5_, Object block, float p_145774_7_);
	public int getMaxSafePointTries();

	public boolean attackEntityFrom(Object damageSource, float amount);
	public void setPositionAndRotation2(double p_180426_1_, double p_180426_3_, double p_180426_5_, float p_180426_7_, float p_180426_8_, int p_180426_9_, boolean p_180426_10_);
	public void onUpdate();
	public void onLivingUpdate();
	public void setCurrentItemOrArmor(int slotIn, Object itemStack);
	public void addChatMessage(Object iChatComponent);
	public Object getPosition();
	public boolean isSpectator();
	public boolean hasPlayerInfo();
	public Object getPlayerInfo();
	public boolean hasSkin();
	public Object getLocationSkin();
	public Object getLocationCape();
	public String getSkinType();
	public float getFovModifier();
	public void applyEntityAttributes();
	public void entityInit();
	public Object getItemInUse();
	public int getItemInUseCount();
	public boolean isUsingItem();
	public int getItemInUseDuration();
	public void stopUsingItem();
	public void clearItemInUse();
	public boolean isBlocking();
	public int getMaxInPortalTime();
	public String getSwimSound();
	public String getSplashSound();
	public int getPortalCooldown();
	public void playSound(String name, float volume, float pitch);
	public void updateItemUse(Object itemStack, int p_71010_2_);
	public void onItemUseFinish();
	public void handleStatusUpdate(byte p_70103_1_);
	public boolean isMovementBlocked();
	public void closeScreen();
	public void updateRidden();
	public void preparePlayerToSpawn();
	public void updateEntityActionState();
	public int getScore();
	public void setScore(int p_85040_1_);
	public void addScore(int p_85039_1_);
	public void onDeath(Object damageSource);
	public String getHurtSound();
	public String getDeathSound();
	public void addToPlayerScore(Object entity, int amount);
	public Object dropOneItem(boolean p_71040_1_);
	public Object dropPlayerItemWithRandomChoice(Object itemStack, boolean unused);
	public Object dropItem(Object itemStack, boolean dropAround, boolean traceItem);
	public void joinEntityItemWithWorld(Object entityItem);
	public float getToolDigEfficiency(Object block);
	public float getBreakSpeed(Object iBlockState, Object blockPos);
	public boolean canHarvestBlock(Object block);
	public void readEntityFromNBT(Object nBTTagCompound);
	public void writeEntityToNBT(Object nBTTagCompound);
	public boolean canAttackPlayer(Object entityPlayer);
	public void damageArmor(float p_70675_1_);
	public int getTotalArmorValue();
	public float getArmorVisibility();
	public void damageEntity(Object damageSource, float damageAmount);
	public void openEditSign(Object tileEntitySign);
	public void openEditCommandBlock(Object commandBlockLogic);
	public void displayVillagerTradeGui(Object iMerchant);
	public void displayGUIChest(Object iInventory);
	public void displayGUIHorse(Object entityHorse, Object iInventory);
	public void displayGui(Object iInteractionObject);
	public void displayGUIBook(Object itemStack);
	public boolean interactWith(Object entity);
	public Object getCurrentEquippedItem();
	public void destroyCurrentEquippedItem();
	public double getYOffset();
	public void attackTargetEntityWithCurrentItem(Object entity);
	public void onCriticalHit(Object entity);
	public void onEnchantmentCritical(Object entity);
	public void respawnPlayer();
	public void setDead();
	public boolean isEntityInsideOpaqueBlock();
	public boolean isUser();
	public Object getGameProfile();
	public Object trySleep(Object blockPos);
	public void wakeUpPlayer(boolean p_70999_1_, boolean updateWorldFlag, boolean setSpawn);
	public float getBedOrientationInDegrees();
	public boolean isPlayerSleeping();
	public boolean isPlayerFullyAsleep();
	public int getSleepTimer();
	public void addChatComponentMessage(Object iChatComponent);
	public Object getBedLocation();
	public boolean isSpawnForced();
	public void setSpawnPoint(Object blockPos, boolean forced);
	public void triggerAchievement(Object statBase);
	public void addStat(Object statBase, int amount);
	public void func_175145_a(Object statBase);
	public void jump();
	public void moveEntityWithHeading(float p_70612_1_, float p_70612_2_);
	public float getAIMoveSpeed();
	public void addMovementStat(double p_71000_1_, double p_71000_3_, double p_71000_5_);
	public void fall(float distance, float damageMultiplier);
	public void resetHeight();
	public String getFallSoundString(int damageValue);
	public void onKillEntity(Object entityLivingBase);
	public void setInWeb();
	public Object getCurrentArmor(int slotIn);
	public void addExperience(int amount);
	public int getXPSeed();
	public void removeExperienceLevel(int levels);
	public void addExperienceLevel(int levels);
	public int xpBarCap();
	public void addExhaustion(float p_71020_1_);
	public Object getFoodStats();
	public boolean canEat(boolean ignoreHunger);
	public boolean shouldHeal();
	public void setItemInUse(Object itemStack, int duration);
	public boolean isAllowEdit();
	public boolean canPlayerEdit(Object blockPos, Object enumFacing, Object itemStack);
	public int getExperiencePoints(Object entityPlayer);
	public boolean isPlayer();
	public boolean getAlwaysRenderNameTagForRender();
	public void clonePlayer(Object entityPlayer, boolean respawnFromEnd);
	public boolean canTriggerWalking();
	public void sendPlayerAbilities();
	public void setGameType(Object gameType);
	public Object getInventoryEnderChest();
	public Object getEquipmentInSlot(int slotIn);
	public Object getHeldItem();
	public boolean isInvisibleToPlayer(Object entityPlayer);
	public Object[] getInventory();
	public boolean isPushedByWater();
	public Object getWorldScoreboard();
	public Object getTeam();
	public Object getDisplayName();
	public float getEyeHeight();
	public void setAbsorptionAmount(float amount);
	public float getAbsorptionAmount();
	public boolean canOpen(Object lockCode);
	public boolean isWearing(Object enumPlayerModelParts);
	public boolean sendCommandFeedback();
	public boolean replaceItemInInventory(int p_174820_1_, Object itemStack);
	public boolean hasReducedDebug();
	public void setReducedDebug(boolean reducedDebug);
	public void openGui(Object mod, int modGuiId, Object world, int x, int y, int z);
	public Object getBedLocation(int dimension);
	public boolean isSpawnForced(int dimension);
	public void setSpawnChunk(Object blockPos, boolean forced, int dimension);
	public float getDefaultEyeHeight();
	public String getDisplayNameString();
	public void refreshDisplayName();
	public void onKillCommand();
	public void updateFallState(double p_180433_1_, boolean p_180433_3_, Object block, Object blockPos);
	public boolean canBreatheUnderwater();
	public void onEntityUpdate();
	public boolean isChild();
	public void onDeathUpdate();
	public boolean canDropLoot();
	public int decreaseAirSupply(int p_70682_1_);
	public Random getRNG();
	public Object getAITarget();
	public int getRevengeTimer();
	public void setRevengeTarget(Object entityLivingBase);
	public Object getLastAttacker();
	public int getLastAttackerTime();
	public void setLastAttacker(Object entity);
	public int getAge();
	public void updatePotionEffects();
	public void updatePotionMetadata();
	public void resetPotionEffectMetadata();
	public void clearActivePotions();
	public Object getActivePotionEffects();
	public boolean isPotionActive(int p_82165_1_);
	public boolean isPotionActive(Object potion);
	public Object getActivePotionEffect(Object potion);
	public void addPotionEffect(Object potionEffect);
	public boolean isPotionApplicable(Object potionEffect);
	public boolean isEntityUndead();
	public void removePotionEffectClient(int p_70618_1_);
	public void removePotionEffect(int p_82170_1_);
	public void onNewPotionEffect(Object potionEffect);
	public void onChangedPotionEffect(Object potionEffect, boolean p_70695_2_);
	public void onFinishedPotionEffect(Object potionEffect);
	public void heal(float healAmount);
	public void setHealth(float p_70606_1_);
	public void renderBrokenItemStack(Object itemStack);
	public void dropEquipment(boolean p_82160_1_, int p_82160_2_);
	public void knockBack(Object entity, float p_70653_2_, double p_70653_3_, double p_70653_5_);
	public void addRandomDrop();
	public void dropFewItems(boolean p_70628_1_, int p_70628_2_);
	public boolean isOnLadder();
	public boolean isEntityAlive();
	public void performHurtAnimation();
	public float applyArmorCalculations(Object damageSource, float p_70655_2_);
	public float applyPotionDamageCalculations(Object damageSource, float p_70672_2_);
	public Object getCombatTracker();
	public Object func_94060_bK();
	public void swingItem();
	public void kill();
	public void updateArmSwingProgress();
	public Object getEntityAttribute(Object iAttribute);
	public Object getAttributeMap();
	public Object getCreatureAttribute();
	public void setSprinting(boolean sprinting);
	public float getSoundVolume();
	public float getSoundPitch();
	public void dismountEntity(Object entity);
	public float getJumpUpwardsMotion();
	public void updateAITick();
	public void handleJumpLava();
	public void setAIMoveSpeed(float p_70659_1_);
	public boolean attackEntityAsMob(Object entity);
	public float func_110146_f(float p_110146_1_, float p_110146_2_);
	public void collideWithNearbyEntities();
	public void collideWithEntity(Object entity);
	public void mountEntity(Object entity);
	public void setJumping(boolean p_70637_1_);
	public void onItemPickup(Object entity, int p_71001_2_);
	public boolean canEntityBeSeen(Object entity);
	public Object getLookVec();
	public Object getLook(float p_70676_1_);
	public float getSwingProgress(float p_70678_1_);
	public boolean isServerWorld();
	public boolean canBeCollidedWith();
	public boolean canBePushed();
	public void setBeenAttacked();
	public float getRotationYawHead();
	public void setRotationYawHead(float rotation);
	public boolean isOnSameTeam(Object entityLivingBase);
	public boolean isOnTeam(Object team);
	public void sendEnterCombat();
	public void sendEndCombat();
	public void markPotionsDirty();
	public void curePotionEffects(Object itemStack);
	public boolean shouldRiderFaceForward(Object entityPlayer);
	public int getEntityId();
	public void setEntityId(int id);
	public Object getDataWatcher();
	public void setSize(float width, float height);
	public void setRotation(float yaw, float pitch);
	public void setPosition(double x, double y, double z);
	public void setAngles(float yaw, float pitch);
	public void setOnFireFromLava();
	public void setFire(int seconds);
	public void extinguish();
	public boolean isOffsetPositionInLiquid(double x, double y, double z);
	public void moveEntity(double x, double y, double z);
	public void doBlockCollisions();
	public void playStepSound(Object blockPos, Object block);
	public boolean isSilent();
	public void setSilent(boolean isSilent);
	public Object getCollisionBoundingBox();
	public void dealFireDamage(int amount);
	public boolean isWet();
	public boolean isInWater();
	public boolean handleWaterMovement();
	public void spawnRunningParticles();
	public void createRunningParticles();
	public boolean isInsideOfMaterial(Object material);
	public boolean isInLava();
	public void moveFlying(float strafe, float forward, float friction);
	public int getBrightnessForRender(float p_70070_1_);
	public float getBrightness(float p_70013_1_);
	public void setWorld(Object world);
	public void setPositionAndRotation(double x, double y, double z, float yaw, float pitch);
	public void moveToBlockPosAndAngles(Object blockPos, float p_174828_2_, float p_174828_3_);
	public void setLocationAndAngles(double x, double y, double z, float yaw, float pitch);
	public float getDistanceToEntity(Object entity);
	public double getDistanceSq(double x, double y, double z);
	public double getDistanceSq(Object blockPos);
	public double getDistanceSqToCenter(Object blockPos);
	public double getDistance(double x, double y, double z);
	public double getDistanceSqToEntity(Object entity);
	public void onCollideWithPlayer(Object entityPlayer);
	public void applyEntityCollision(Object entity);
	public void addVelocity(double x, double y, double z);
	public Object getPositionEyes(float p_174824_1_);
	public Object rayTrace(double p_174822_1_, float p_174822_3_);
	public boolean isInRangeToRender3d(double x, double y, double z);
	public boolean isInRangeToRenderDist(double distance);
	public boolean writeMountToNBT(Object nBTTagCompound);
	public boolean writeToNBTOptional(Object nBTTagCompound);
	public void writeToNBT(Object nBTTagCompound);
	public void readFromNBT(Object nBTTagCompound);
	public boolean shouldSetPosAfterLoading();
	public void onChunkLoad();
	public Object newDoubleNBTList(double... numbers);
	public Object newFloatNBTList(float... numbers);
	public Object dropItem(Object item, int size);
	public Object dropItemWithOffset(Object item, int size, float p_145778_3_);
	public Object entityDropItem(Object itemStack, float offsetY);
	public boolean interactFirst(Object entityPlayer);
	public Object getCollisionBox(Object entity);
	public void updateRiderPosition();
	public double getMountedYOffset();
	public float getCollisionBorderSize();
	public void setPortal(Object bockPos);
	public void setVelocity(double x, double y, double z);
	public boolean isBurning();
	public boolean isRiding();
	public boolean isSneaking();
	public void setSneaking(boolean sneaking);
	public boolean isSprinting();
	public boolean isInvisible();
	public void setInvisible(boolean invisible);
	public boolean isEating();
	public void setEating(boolean eating);
	public boolean getFlag(int flag);
	public void setFlag(int flag, boolean set);
	public int getAir();
	public void setAir(int air);
	public void onStruckByLightning(Object entityLightningBolt);
	public boolean pushOutOfBlocks(double x, double y, double z);
	public Object[] getParts();
	public boolean isEntityEqual(Object entity);
	public boolean canAttackWithItem();
	public boolean hitByEntity(Object entity);
	public boolean isEntityInvulnerable(Object damageSource);
	public void copyLocationAndAnglesFrom(Object entity);
	public void copyDataFromOld(Object entity);
	public void travelToDimension(int dimensionId);
	public float getExplosionResistance(Object explosion, Object world, Object blockPos, Object iBlockState);
	public boolean verifyExplosion(Object explosion, Object world, Object blockPos, Object iBlockState, float p_174816_5_);
	public int getMaxFallHeight();
	public Object getTeleportDirection();
	public boolean doesEntityNotTriggerPressurePlate();
	public void addEntityCrashInfo(Object crashReportCategory);
	public boolean canRenderOnFire();
	public UUID getUniqueID();
	public void setCustomNameTag(String p_96094_1_);
	public String getCustomNameTag();
	public boolean hasCustomName();
	public void setAlwaysRenderNameTag(boolean p_174805_1_);
	public boolean getAlwaysRenderNameTag();
	public void setPositionAndUpdate(double x, double y, double z);
	public void onDataWatcherUpdate(int p_145781_1_);
	public Object getHorizontalFacing();
	public Object getHoverEvent();
	public boolean isSpectatedByPlayer(Object entityPlayerMP);
	public Object getEntityBoundingBox();
	public void setEntityBoundingBox(Object axisAlignedBB);
	public boolean isOutsideBorder();
	public void setOutsideBorder(boolean p_174821_1_);
	public Object getPositionVector();
	public Object getEntityWorld();
	public Object getCommandSenderEntity();
	public void setCommandStat(Object type, int amount);
	public Object getCommandStats();
	public void func_174817_o(Object entity);
	public Object getNBTTagCompound();
	public void clientUpdateEntityNBT(Object nBTTagCompound);
	public boolean interactAt(Object entityPlayer, Object vec3);
	public boolean isImmuneToExplosions();
	public void applyEnchantments(Object entityLivingBase, Object entity);
	public Object getEntityData();
	public boolean shouldRiderSit();
	public Object getPickedResult(Object movingObjectPosition);
	public UUID getPersistentID();
	public boolean shouldRenderInPass(int pass);
	public boolean isCreatureType(Object enumCreatureType, boolean forSpawnCount);
	public String registerExtendedProperties(String identifier, Object iExtendedEntityProperties);
	public Object getExtendedProperties(String identifier);
	public boolean canRiderInteract();
	public boolean shouldDismountInWater(Object entity);

}
