package modchu.lib;

public interface Modchu_IEntityTameable extends Modchu_IEntityLiving {
	public Object superFunc_110172_bL();
	public void superAttackEntity(Object entity, float par2);
	public float superGetBlockPathWeight(int par1, int par2, int par3);
	public Object superFindPlayerToAttack();
	public boolean superIsMovementCeased();
	public void superUpdateWanderPath();
	public void superSetPathToEntity(Object pathEntity);
	public Object superGetEntityToAttack();
	public void superSetTarget(Object entity);
	public void superEnablePersistence();
	public void superEnchantEquipment();
	public boolean superHasCustomNameTag();
	public void superSetInLove(Object entityPlayer);
	public float superGetExplosionResistance(Object explosion, Object world, int p_145772_3_, int p_145772_4_, int p_145772_5_, Object block);
	public String superFunc_152113_b();
	public void superFunc_152115_b(String par1Str);
	public String superFunc_146067_o(int p_146067_1_);
	public void superPlayTameEffect(boolean par1);
	public boolean superIsTamed();
	public void superSetTamed(boolean par1);
	public boolean superIsSitting();
	public void superSetSitting(boolean par1);
	public Object superGetOwnerName();
	public void superSetOwner(Object par1Str);
	public Object superGetAISit();
	public boolean superShouldAttackEntity(Object entityLivingBase, Object entityLivingBase1);
	public boolean superIsBreedingItem(Object itemStack);
	public boolean superIsInLove();
	public void superResetInLove();
	public boolean superCanMateWith(Object entityAnimal);
	public int superGetGrowingAge();
	public void superAddGrowth(int par1);
	public void superSetGrowingAge(int par1);
	public void superSetScaleForAge(boolean par1);
	public boolean superHasPath();
	public void superOnLeashDistance(float par1);
	public void superClearLeashed(boolean par1, boolean par2);
	public boolean superCanBeLeashedTo();
	public boolean superGetLeashed();
	public Object superGetLeashedToEntity();
	public void superSetLeashedToEntity(Object entity, boolean par2);
	public void superCopyDataFrom(Object entity);
	public Object superFunc_130012_q();
	public void superFunc_110196_bT();
	public boolean superFunc_110176_b(int par1, int par2, int par3);
	public void superUpdateLeashedState();
	public boolean superIsWithinHomeDistanceCurrentPosition();
	public int superGetDropItemId();
	public void superSetCurrentItemOrArmor(int par1, Object itemStack);
	public boolean superProcessInteract(Object entityPlayer);
	public void superAddRandomArmor();
	// ~152
	public int superGetHealthInt();
	public float superGetHealthFloat();
	// 180~
	public void superSetupTamedAI();
	public Object superGetOwner();
	public boolean superIsOwner(Object entityLivingBase);
	public float superGetBlockPathWeight(Object blockPos);
	public void superConsumeItemFromStack(Object entityPlayer, Object itemStack);
	public Object superGetLoveCause();
	public void superAgeUp(int p_175501_1_, boolean p_175501_2_);
	public void superOnGrowingAdult();
	public boolean superIsWithinHomeDistanceFromPosition(Object blockPos);
	public void superSetHomePosAndDistance(Object blockPos, int distance);
	public Object superCreateNavigator(Object world);
	public Object superGetDropItem();
	public void superUpdateEquipmentIfNeeded(Object entityItem);
	public boolean superCanEquipItem(Object itemStack);
	public void superSetEquipmentBasedOnDifficulty(Object difficultyInstance);
	public void superSetEnchantmentBasedOnDifficulty(Object difficultyInstance);
	public boolean superIsAIDisabled();
	public String superGetCommandSenderName();
	// 190~
	public boolean superProcessInteract(Object entityPlayer, Object enumHand, Object itemStack);
	public boolean superCanBeLeashedTo(Object entityPlayer);
	public float superGetPathPriority(Object pathNodeType);
	public void superInitEntityAI();
	public void superSetPathPriority(Object pathNodeType, float p_184644_2_);
	public Object superCreateBodyHelper();
	public Object superGetLootTable();
	public void superSetMoveStrafing(float p_184646_1_);
	public int superGetHorizontalFaceSpeed();
	public Object superGetPrimaryHand();
	public void superSetLeftHanded(boolean p_184641_1_);
	public boolean superIsLeftHanded();
	public Object superOnInitialSpawn(Object difficultyInstance, Object iEntityLivingData);

	public boolean superFunc_152114_e(Object entityLivingBase);
	public Object superFunc_146083_cb();
	public Object superFunc_110142_aN();
	public void superFunc_175501_a(int p_175501_1_, boolean p_175501_2_);
	public Object superGetNewNavigator(Object world);
	public boolean superFunc_175448_a(Object itemStack);
	public void superSetTamedBy(Object entityPlayer);
	public boolean superHoldingSpawnEggOfClass(Object itemStack, Class p_190669_2_);
	public double superFollowLeashSpeed();
	public void superSetMoveForward(float p_191989_1_);
	public Object superGetHurtSound(Object damageSource);
	public void superTravel(float p_191986_1_, float p_191986_2_, float p_191986_3_);

}
