package modchu.lib;

import java.util.Random;
import java.util.UUID;

public interface Modchu_IEntityOtherPlayerMP {
	public boolean superAttackEntityFrom(Object damageSource, float amount);
	public void superFunc_180426_a(double p_180426_1_, double p_180426_3_, double p_180426_5_, float p_180426_7_, float p_180426_8_, int p_180426_9_, boolean p_180426_10_);
	public void superOnUpdate();
	public void superOnLivingUpdate();
	public void superSetCurrentItemOrArmor(int slotIn, Object itemStack);
	public void superAddChatMessage(Object iChatComponent);
	public boolean superCanUseCommand(int permLevel, String commandName);
	public Object superGetPosition();
	public boolean superIsSpectator();
	public boolean superHasPlayerInfo();
	public Object superGetPlayerInfo();
	public boolean superHasSkin();
	public Object superGetLocationSkin();
	public Object superGetLocationCape();
	public String superGetSkinType();
	public float superGetFovModifier();
	public void superApplyEntityAttributes();
	public void superEntityInit();
	public Object superGetItemInUse();
	public int superGetItemInUseCount();
	public boolean superIsUsingItem();
	public int superGetItemInUseDuration();
	public void superStopUsingItem();
	public void superClearItemInUse();
	public boolean superIsBlocking();
	public int superGetMaxInPortalTime();
	public String superGetSwimSound();
	public String superGetSplashSound();
	public int superGetPortalCooldown();
	public void superPlaySound(String name, float volume, float pitch);
	public void superUpdateItemUse(Object itemStack, int p_71010_2_);
	public void superOnItemUseFinish();
	public void superHandleHealthUpdate(byte p_70103_1_);
	public boolean superIsMovementBlocked();
	public void superCloseScreen();
	public void superUpdateRidden();
	public void superPreparePlayerToSpawn();
	public void superUpdateEntityActionState();
	public int superGetScore();
	public void superSetScore(int p_85040_1_);
	public void superAddScore(int p_85039_1_);
	public void superOnDeath(Object damageSource);
	public String superGetHurtSound();
	public String superGetDeathSound();
	public void superAddToPlayerScore(Object entity, int amount);
	public Object superDropOneItem(boolean p_71040_1_);
	public Object superDropPlayerItemWithRandomChoice(Object itemStack, boolean unused);
	public Object superDropItem(Object itemStack, boolean dropAround, boolean traceItem);
	public void superJoinEntityItemWithWorld(Object entityItem);
	public float superGetToolDigEfficiency(Object block);
	public float superGetBreakSpeed(Object iBlockState, Object blockPos);
	public boolean superCanHarvestBlock(Object block);
	public void superReadEntityFromNBT(Object nBTTagCompound);
	public void superWriteEntityToNBT(Object nBTTagCompound);
	public boolean superCanAttackPlayer(Object entityPlayer);
	public void superDamageArmor(float p_70675_1_);
	public int superGetTotalArmorValue();
	public float superGetArmorVisibility();
	public void superDamageEntity(Object damageSource, float damageAmount);
	public void superOpenEditSign(Object tileEntitySign);
	public void superOpenEditCommandBlock(Object commandBlockLogic);
	public void superDisplayVillagerTradeGui(Object iMerchant);
	public void superDisplayGUIChest(Object iInventory);
	public void superDisplayGUIHorse(Object entityHorse, Object iInventory);
	public void superDisplayGui(Object iInteractionObject);
	public void superDisplayGUIBook(Object itemStack);
	public boolean superInteractWith(Object entity);
	public Object superGetCurrentEquippedItem();
	public void superDestroyCurrentEquippedItem();
	public double superGetYOffset();
	public void superAttackTargetEntityWithCurrentItem(Object entity);
	public void superOnCriticalHit(Object entity);
	public void superOnEnchantmentCritical(Object entity);
	public void superRespawnPlayer();
	public void superSetDead();
	public boolean superIsEntityInsideOpaqueBlock();
	public boolean superIsUser();
	public Object superGetGameProfile();
	public Object superTrySleep(Object blockPos);
	public void superWakeUpPlayer(boolean p_70999_1_, boolean updateWorldFlag, boolean setSpawn);
	public float superGetBedOrientationInDegrees();
	public boolean superIsPlayerSleeping();
	public boolean superIsPlayerFullyAsleep();
	public int superGetSleepTimer();
	public void superAddChatComponentMessage(Object iChatComponent);
	public Object superGetBedLocation();
	public boolean superIsSpawnForced();
	public void superSetSpawnPoint(Object blockPos, boolean forced);
	public void superTriggerAchievement(Object statBase);
	public void superAddStat(Object statBase, int amount);
	public void superFunc_175145_a(Object statBase);
	public void superJump();
	public void superMoveEntityWithHeading(float p_70612_1_, float p_70612_2_);
	public float superGetAIMoveSpeed();
	public void superAddMovementStat(double p_71000_1_, double p_71000_3_, double p_71000_5_);
	public void superFall(float distance, float damageMultiplier);
	public void superResetHeight();
	public String superGetFallSoundString(int damageValue);
	public void superOnKillEntity(Object entityLivingBase);
	public void superSetInWeb();
	public Object superGetCurrentArmor(int slotIn);
	public void superAddExperience(int amount);
	public int superGetXPSeed();
	public void superRemoveExperienceLevel(int levels);
	public void superAddExperienceLevel(int levels);
	public int superXpBarCap();
	public void superAddExhaustion(float p_71020_1_);
	public Object superGetFoodStats();
	public boolean superCanEat(boolean ignoreHunger);
	public boolean superShouldHeal();
	public void superSetItemInUse(Object itemStack, int duration);
	public boolean superIsAllowEdit();
	public boolean superCanPlayerEdit(Object blockPos, Object enumFacing, Object itemStack);
	public int superGetExperiencePoints(Object entityPlayer);
	public boolean superIsPlayer();
	public boolean superGetAlwaysRenderNameTagForRender();
	public void superClonePlayer(Object entityPlayer, boolean respawnFromEnd);
	public boolean superCanTriggerWalking();
	public void superSendPlayerAbilities();
	public void superSetGameType(Object gameType);
	public String superGetName();
	public Object superGetInventoryEnderChest();
	public Object superGetEquipmentInSlot(int slotIn);
	public Object superGetHeldItem();
	public boolean superIsInvisibleToPlayer(Object entityPlayer);
	public Object[] superGetInventory();
	public boolean superIsPushedByWater();
	public Object superGetWorldScoreboard();
	public Object superGetTeam();
	public Object superGetDisplayName();
	public float superGetEyeHeight();
	public void superSetAbsorptionAmount(float amount);
	public float superGetAbsorptionAmount();
	public boolean superCanOpen(Object lockCode);
	public boolean superFunc_175148_a(Object enumPlayerModelParts);
	public boolean superSendCommandFeedback();
	public boolean superReplaceItemInInventory(int p_174820_1_, Object itemStack);
	public boolean superHasReducedDebug();
	public void superSetReducedDebug(boolean reducedDebug);
	public void superOpenGui(Object mod, int modGuiId, Object world, int x, int y, int z);
	public Object superGetBedLocation(int dimension);
	public boolean superIsSpawnForced(int dimension);
	public void superSetSpawnChunk(Object blockPos, boolean forced, int dimension);
	public float superGetDefaultEyeHeight();
	public String superGetDisplayNameString();
	public void superRefreshDisplayName();
	public void superOnKillCommand();
	public void superFunc_180433_a(double p_180433_1_, boolean p_180433_3_, Object block, Object blockPos);
	public boolean superCanBreatheUnderwater();
	public void superOnEntityUpdate();
	public boolean superIsChild();
	public void superOnDeathUpdate();
	public boolean superFunc_146066_aG();
	public int superDecreaseAirSupply(int p_70682_1_);
	public Random superGetRNG();
	public Object superGetAITarget();
	public int superGetRevengeTimer();
	public void superSetRevengeTarget(Object entityLivingBase);
	public Object superGetLastAttacker();
	public int superGetLastAttackerTime();
	public void superSetLastAttacker(Object entity);
	public int superGetAge();
	public void superUpdatePotionEffects();
	public void superFunc_175135_B();
	public void superFunc_175133_bi();
	public void superClearActivePotions();
	public Object superGetActivePotionEffects();
	public boolean superIsPotionActive(int p_82165_1_);
	public boolean superIsPotionActive(Object potion);
	public Object superGetActivePotionEffect(Object potion);
	public void superAddPotionEffect(Object potionEffect);
	public boolean superIsPotionApplicable(Object potionEffect);
	public boolean superIsEntityUndead();
	public void superRemovePotionEffectClient(int p_70618_1_);
	public void superRemovePotionEffect(int p_82170_1_);
	public void superOnNewPotionEffect(Object potionEffect);
	public void superOnChangedPotionEffect(Object potionEffect, boolean p_70695_2_);
	public void superOnFinishedPotionEffect(Object potionEffect);
	public void superHeal(float healAmount);
	public void superSetHealth(float p_70606_1_);
	public void superRenderBrokenItemStack(Object itemStack);
	public void superDropEquipment(boolean p_82160_1_, int p_82160_2_);
	public void superKnockBack(Object entity, float p_70653_2_, double p_70653_3_, double p_70653_5_);
	public void superAddRandomArmor();
	public void superDropFewItems(boolean p_70628_1_, int p_70628_2_);
	public boolean superIsOnLadder();
	public boolean superIsEntityAlive();
	public void superPerformHurtAnimation();
	public float superApplyArmorCalculations(Object damageSource, float p_70655_2_);
	public float superApplyPotionDamageCalculations(Object damageSource, float p_70672_2_);
	public Object superGetCombatTracker();
	public Object superFunc_94060_bK();
	public void superSwingItem();
	public void superKill();
	public void superUpdateArmSwingProgress();
	public Object superGetEntityAttribute(Object iAttribute);
	public Object superGetAttributeMap();
	public Object superGetCreatureAttribute();
	public void superSetSprinting(boolean sprinting);
	public float superGetSoundVolume();
	public float superGetSoundPitch();
	public void superDismountEntity(Object entity);
	public float superFunc_175134_bD();
	public void superUpdateAITick();
	public void superFunc_180466_bG();
	public void superSetAIMoveSpeed(float p_70659_1_);
	public boolean superAttackEntityAsMob(Object entity);
	public float superFunc_110146_f(float p_110146_1_, float p_110146_2_);
	public void superCollideWithNearbyEntities();
	public void superCollideWithEntity(Object entity);
	public void superMountEntity(Object entity);
	public void superSetJumping(boolean p_70637_1_);
	public void superOnItemPickup(Object entity, int p_71001_2_);
	public boolean superCanEntityBeSeen(Object entity);
	public Object superGetLookVec();
	public Object superGetLook(float p_70676_1_);
	public float superGetSwingProgress(float p_70678_1_);
	public boolean superIsServerWorld();
	public boolean superCanBeCollidedWith();
	public boolean superCanBePushed();
	public void superSetBeenAttacked();
	public float superGetRotationYawHead();
	public void superSetRotationYawHead(float rotation);
	public boolean superIsOnSameTeam(Object entityLivingBase);
	public boolean superIsOnTeam(Object team);
	public void superFunc_152111_bt();
	public void superFunc_152112_bu();
	public void superFunc_175136_bO();
	public void superCurePotionEffects(Object itemStack);
	public boolean superShouldRiderFaceForward(Object entityPlayer);
	public int superGetEntityId();
	public void superSetEntityId(int id);
	public Object superGetDataWatcher();
	public boolean superEquals(Object p_equals_1_);
	public int superHashCode();
	public void superSetSize(float width, float height);
	public void superSetRotation(float yaw, float pitch);
	public void superSetPosition(double x, double y, double z);
	public void superSetAngles(float yaw, float pitch);
	public void superSetOnFireFromLava();
	public void superSetFire(int seconds);
	public void superExtinguish();
	public boolean superIsOffsetPositionInLiquid(double x, double y, double z);
	public void superMoveEntity(double x, double y, double z);
	public void superDoBlockCollisions();
	public void superPlayStepSound(Object blockPos, Object block);
	public boolean superIsSilent();
	public void superSetSilent(boolean isSilent);
	public Object superGetBoundingBox();
	public void superDealFireDamage(int amount);
	public boolean superIsWet();
	public boolean superIsInWater();
	public boolean superHandleWaterMovement();
	public void superSpawnRunningParticles();
	public void superCreateRunningParticles();
	public boolean superIsInsideOfMaterial(Object material);
	public boolean superIsInLava();
	public void superMoveFlying(float strafe, float forward, float friction);
	public int superGetBrightnessForRender(float p_70070_1_);
	public float superGetBrightness(float p_70013_1_);
	public void superSetWorld(Object world);
	public void superSetPositionAndRotation(double x, double y, double z, float yaw, float pitch);
	public void superMoveToBlockPosAndAngles(Object blockPos, float p_174828_2_, float p_174828_3_);
	public void superSetLocationAndAngles(double x, double y, double z, float yaw, float pitch);
	public float superGetDistanceToEntity(Object entity);
	public double superGetDistanceSq(double x, double y, double z);
	public double superGetDistanceSq(Object blockPos);
	public double superGetDistanceSqToCenter(Object blockPos);
	public double superGetDistance(double x, double y, double z);
	public double superGetDistanceSqToEntity(Object entity);
	public void superOnCollideWithPlayer(Object entityPlayer);
	public void superApplyEntityCollision(Object entity);
	public void superAddVelocity(double x, double y, double z);
	public Object superGetPositionEyes(float p_174824_1_);
	public Object superRayTrace(double p_174822_1_, float p_174822_3_);
	public boolean superIsInRangeToRender3d(double x, double y, double z);
	public boolean superIsInRangeToRenderDist(double distance);
	public boolean superWriteMountToNBT(Object nBTTagCompound);
	public boolean superWriteToNBTOptional(Object nBTTagCompound);
	public void superWriteToNBT(Object nBTTagCompound);
	public void superReadFromNBT(Object nBTTagCompound);
	public boolean superShouldSetPosAfterLoading();
	public void superOnChunkLoad();
	public Object superNewDoubleNBTList(double... numbers);
	public Object superNewFloatNBTList(float... numbers);
	public Object superDropItem(Object item, int size);
	public Object superDropItemWithOffset(Object item, int size, float p_145778_3_);
	public Object superEntityDropItem(Object itemStack, float offsetY);
	public boolean superInteractFirst(Object entityPlayer);
	public Object superGetCollisionBox(Object entity);
	public void superUpdateRiderPosition();
	public double superGetMountedYOffset();
	public float superGetCollisionBorderSize();
	public void superSetInPortal();
	public void superSetVelocity(double x, double y, double z);
	public boolean superIsBurning();
	public boolean superIsRiding();
	public boolean superIsSneaking();
	public void superSetSneaking(boolean sneaking);
	public boolean superIsSprinting();
	public boolean superIsInvisible();
	public void superSetInvisible(boolean invisible);
	public boolean superIsEating();
	public void superSetEating(boolean eating);
	public boolean superGetFlag(int flag);
	public void superSetFlag(int flag, boolean set);
	public int superGetAir();
	public void superSetAir(int air);
	public void superOnStruckByLightning(Object entityLightningBolt);
	public boolean superPushOutOfBlocks(double x, double y, double z);
	public Object[] superGetParts();
	public boolean superIsEntityEqual(Object entity);
	public boolean superCanAttackWithItem();
	public boolean superHitByEntity(Object entity);
	public String superToString();
	public boolean superIsEntityInvulnerable(Object damageSource);
	public void superCopyLocationAndAnglesFrom(Object entity);
	public void superCopyDataFromOld(Object entity);
	public void superTravelToDimension(int dimensionId);
	public float superGetExplosionResistance(Object explosion, Object world, Object blockPos, Object iBlockState);
	public boolean superFunc_174816_a(Object explosion, Object world, Object blockPos, Object iBlockState, float p_174816_5_);
	public int superGetMaxFallHeight();
	public int superGetTeleportDirection();
	public boolean superDoesEntityNotTriggerPressurePlate();
	public void superAddEntityCrashInfo(Object crashReportCategory);
	public boolean superCanRenderOnFire();
	public UUID superGetUniqueID();
	public void superSetCustomNameTag(String p_96094_1_);
	public String superGetCustomNameTag();
	public boolean superHasCustomName();
	public void superSetAlwaysRenderNameTag(boolean p_174805_1_);
	public boolean superGetAlwaysRenderNameTag();
	public void superSetPositionAndUpdate(double x, double y, double z);
	public void superFunc_145781_i(int p_145781_1_);
	public Object superGetHorizontalFacing();
	public Object superFunc_174823_aP();
	public boolean superFunc_174827_a(Object entityPlayerMP);
	public Object superGetEntityBoundingBox();
	public void superSetEntityBoundingBox(Object axisAlignedBB);
	public boolean superIsOutsideBorder();
	public void superSetOutsideBorder(boolean p_174821_1_);
	public Object superGetPositionVector();
	public Object superGetEntityWorld();
	public Object superGetCommandSenderEntity();
	public void superSetCommandStat(Object type, int amount);
	public Object superFunc_174807_aT();
	public void superFunc_174817_o(Object entity);
	public Object superFunc_174819_aU();
	public void superFunc_174834_g(Object nBTTagCompound);
	public boolean superFunc_174825_a(Object entityPlayer, Object vec3);
	public boolean superFunc_180427_aV();
	public void superFunc_174815_a(Object entityLivingBase, Object entity);
	public Object superGetEntityData();
	public boolean superShouldRiderSit();
	public Object superGetPickedResult(Object movingObjectPosition);
	public UUID superGetPersistentID();
	public boolean superShouldRenderInPass(int pass);
	public boolean superIsCreatureType(Object enumCreatureType, boolean forSpawnCount);
	public String superRegisterExtendedProperties(String identifier, Object iExtendedEntityProperties);
	public Object superGetExtendedProperties(String identifier);
	public boolean superCanRiderInteract();
	public boolean superShouldDismountInWater(Object entity);

}
